import assert from 'node:assert/strict';
import {decodeQuote,mergeStream} from '../lib/quote-stream.ts';
import {demo} from '../lib/market.ts';
const wire='{"type":"pricing","message":"CgROVkRBFeAdZ0MYsLXWkp9oKgNOTVMwCDgCRc644z1lAG6DPtgBBPUCACYvQP0CImKZPw=="}';
const tick=decodeQuote(wire,1800000000000);
assert.equal(tick.symbol,'NVDA');assert.ok(tick.price>200&&tick.price<300);assert.equal(tick.marketHours,2);assert.ok(tick.timestamp>1700000000000);assert.equal(decodeQuote('bad'),null);assert.equal(decodeQuote('{"type":"heartbeat"}'),null);
const snapshot={...demo('NVDA'),timestamp:tick.timestamp-1000,price:200,points:[{time:tick.timestamp-300000,price:200,volume:100}]};
assert.equal(mergeStream(snapshot,tick,'1D').price,tick.price);
assert.deepEqual(mergeStream(snapshot,tick,'1D').points,snapshot.points,'after-hours prices must not enter regular-session chart');
assert.equal(mergeStream({...snapshot,timestamp:tick.timestamp+1000},tick,'1D').price,200,'older stream quote must not replace newer snapshot');
assert.equal(mergeStream({...snapshot,symbol:'AAPL'},tick,'1D').price,200,'quotes cannot cross symbols');
const regular={...tick,marketHours:1};assert.equal(mergeStream(snapshot,regular,'1D').points.at(-1).price,tick.price);assert.deepEqual(mergeStream(snapshot,regular,'1Y').points,snapshot.points);
console.log('PASS: real frame decoding, malformed data, stale quotes, symbol isolation, and session-aware chart updates');
const nextDay={...regular,timestamp:regular.timestamp+86400000};
assert.equal(mergeStream(snapshot,nextDay,'1D').points.length,1,'a new regular session resets the prior-day line');
assert.equal(mergeStream({...snapshot,points:[]},regular,'1D').points.length,1,'first regular trade can seed an empty intraday chart');
