import {LegalPage} from '@/components/legal/legal-page';
export default function PrivacyPage(){return <LegalPage title="Privacy notice">
<section><h2>Data we process</h2><p>Account email, user ID, account creation and sign-in dates, and identity information supplied by your chosen Google or email authentication provider. Saved stock symbols, company names and watchlist update times are linked to your account. Authentication services and hosting providers may process IP addresses, device information and operational/security logs.</p><p>We use account and saved-stock data for sign-in and watchlist syncing. Current features do not request national ID, bank-account or invested-balance information.</p></section>
<section><h2>Purposes and legal bases</h2><p>Account authentication and watchlist sync are needed to provide the service you request (contractual necessity). Proportionate operational and security processing supports legitimate interests in keeping the service reliable and preventing abuse. Optional usage analytics is enabled only when you choose to allow it; you can withdraw that choice through Privacy settings. No marketing subscription is created by signing up.</p></section>
<section><h2>Providers and international processing</h2><p>Supabase provides authentication and account/watchlist storage. Google receives authentication requests when you choose Google sign-in. Vercel provides hosting and optional analytics. Yahoo receives quote subscriptions from your browser; external logo and news services may receive network/device information when content or links load. These providers may process data outside Thailand. Provider locations, agreements and international-transfer safeguards require operator verification before commercial launch.</p></section>
<section><h2>Browser storage</h2><p>Essential storage saves authentication sessions, the Remember me preference, guest watchlists, motion preferences and privacy preferences. Remember me keeps the login on this browser; without it, the session is stored for the tab. Opening an email sign-in link may require the browser where you requested it. Optional analytics is separate from these essential functions.</p></section>
<section><h2>Retention and rights</h2><p>Saved watchlists are retained while your account exists. Guest data remains in your browser until cleared. Account deletion removes the active account and its linked watchlist; provider security logs and backups follow separately verified retention periods. We do not promise instant deletion from backups.</p><p>You may request access, a copy, correction, deletion, restriction, objection or portability where applicable, and withdraw optional analytics permission. Account & privacy lets you export your account/watchlist and clear local preferences. Deletion is available when secure account administration is configured. Other requests use the operator contact below. Rights are subject to applicable legal exceptions; you may complain to Thailand’s Personal Data Protection Committee.</p></section>
<section><h2>Security</h2><p>Watchlist access is restricted to its account owner using database row-level security. Administrative credentials stay on the server. These measures reduce risk; they do not guarantee that a service can never suffer a security incident. The operator must maintain an incident-response process and comply with applicable breach-notification obligations.</p></section>
</LegalPage>}
