'use client';
import {useEffect,useState} from 'react';
import {Globe2,Search,RefreshCw,BookOpen,ChartNoAxesCombined,Info,Plug,Star,Plus,ChevronLeft,ChevronRight,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {companies,demo,type Market} from '@/lib/market';
import {useQuoteStream} from '@/components/market/use-quote-stream';
import {mergeStream} from '@/lib/quote-stream';
import {NewsFeed} from '@/components/market/news-feed';
import {PriceChart,EarningsChart} from '@/components/market/charts';
const money=(n:number|null)=>n===null?'—':n.toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2});
const ratio=(n:number|null)=>n===null?'Unavailable':n<=0?'N/M':`${n.toFixed(1)}x`;
export default function Home(){const [symbol,setSymbol]=useState('NVDA'),[range,setRange]=useState('1D'),[snapshot,setData]=useState<Market>(demo('NVDA')),[loading,setLoading]=useState(false),[connection,setConnection]=useState(false),[query,setQuery]=useState(''),[search,setSearch]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);const [nav,setNav]=useState('dashboard');
const [watchlist,setWatchlist]=useState<{symbol:string;name:string}[]>(companies.map(({symbol,name})=>({symbol,name}))),[watchReady,setWatchReady]=useState(false),[watchPage,setWatchPage]=useState(0),[searchResults,setSearchResults]=useState<{symbol:string;name:string;exchange:string}[]>([]),[searching,setSearching]=useState(false),[searchError,setSearchError]=useState('');
const stream=useQuoteStream([...watchlist.map(c=>c.symbol),symbol]);
const selectedTick=stream.quotes[symbol];const data=mergeStream(snapshot,selectedTick,range);
const usingStream=!!selectedTick&&selectedTick.timestamp>=(snapshot.timestamp??0);
const tickAge=selectedTick?Math.max(0,Math.floor((stream.now-selectedTick.timestamp)/1000)):null;
const streamStatus=stream.connection==='connected'?(usingStream&&tickAge!==null&&tickAge<30?'LIVE STREAM':usingStream?'AWAITING UPDATE':'STREAM CONNECTED'):stream.connection==='connecting'?'CONNECTING':'RECONNECTING';
const liveSession=selectedTick?.marketHours===0?'Pre-market':selectedTick?.marketHours===2?'After-hours':selectedTick?.marketHours===3?'Extended hours':'Regular session';
useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('market-after-hours-watchlist')||'null');if(Array.isArray(saved)&&saved.length&&saved.length<=24&&saved.every(c=>typeof c.name==='string'&&/^[A-Z][A-Z0-9.-]{0,11}$/.test(c.symbol))){setWatchlist(saved);setSymbol(saved[0].symbol)}}catch{}setWatchReady(true)},[]);
useEffect(()=>{if(watchReady){try{localStorage.setItem('market-after-hours-watchlist',JSON.stringify(watchlist))}catch{}}},[watchlist,watchReady]);
useEffect(()=>{if(!query.trim()){setSearchResults([]);setSearchError('');setSearching(false);return}let active=true;const controller=new AbortController();setSearching(true);const timer=setTimeout(async()=>{try{const r=await fetch(`/api/search?q=${encodeURIComponent(query.trim())}`,{signal:controller.signal});if(!r.ok)throw Error('Search is temporarily unavailable. Please try again.');const results=await r.json();if(active){setSearchResults(results as any);setSearchError('')}}catch(e){if(active){setSearchError(e instanceof Error?e.message:'Search unavailable');setSearchResults([])}}finally{if(active)setSearching(false)}},300);return()=>{active=false;controller.abort();clearTimeout(timer)}},[query]);
function addStock(stock:{symbol:string;name:string}){if(!watchlist.some(c=>c.symbol===stock.symbol)){if(watchlist.length>=24){setSearchError('Your watchlist holds up to 24 stocks. Remove one before adding another.');return}setWatchlist(prev=>[...prev,stock]);setWatchPage(Math.floor(watchlist.length/4))}else setWatchPage(Math.floor(watchlist.findIndex(c=>c.symbol===stock.symbol)/4));setSymbol(stock.symbol);setSearch(false);setQuery('')}
function removeStock(ticker:string){if(watchlist.length<=1)return;const next=watchlist.filter(c=>c.symbol!==ticker);setWatchlist(next);setWatchPage(p=>Math.min(p,Math.floor((next.length-1)/4)));if(symbol===ticker)setSymbol(next[0].symbol)}
 const [watchSnapshots,setWatchQuotes]=useState<Record<string,{price:number|null;percent:number|null;timestamp?:number;points:number[]}>>({});
const watchQuotes=Object.fromEntries(watchlist.map(co=>{const saved=watchSnapshots[co.symbol];const tick=stream.quotes[co.symbol];return [co.symbol,tick&&tick.timestamp>=(saved?.timestamp??0)?{...saved,price:tick.price,percent:tick.percent,points:saved?.points??[],timestamp:tick.timestamp}:saved]}));
useEffect(()=>{let active=true;const run=()=>fetch(`/api/watchlist?symbols=${encodeURIComponent(watchlist.map(c=>c.symbol).join(','))}`).then(r=>r.json()).then(d=>{if(active)setWatchQuotes(d as any)}).catch(()=>{});run();const timer=setInterval(run,60000);return()=>{active=false;clearInterval(timer)}},[watchlist]);
useEffect(()=>{let active=true;const controller=new AbortController();async function run(){setLoading(true);setError('');try{const r=await fetch(`/api/market?symbol=${symbol}&range=${range}`,{signal:controller.signal});if(!r.ok)throw Error('Yahoo Finance is temporarily unavailable. Please refresh.');const result=await r.json() as Market;if(active)setData(result);}catch(e){if(active)setError(e instanceof Error?e.message:'Unable to refresh.');}finally{if(active)setLoading(false)}}setData(prev=>prev.symbol===symbol?{...prev,points:[]}:demo(symbol,range));run();const timer=setInterval(run,60000);return()=>{active=false;controller.abort();clearInterval(timer)}},[symbol,range,refresh]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'select_stock',description:'Select a supported US stock in the visible dashboard.',inputSchema:{type:'object',properties:{symbol:{type:'string',enum:watchlist.map(c=>c.symbol)}},required:['symbol'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(!watchlist.some(c=>c.symbol===input?.symbol))throw Error('Unsupported stock');setSymbol(input.symbol);return {selected:input.symbol}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[watchlist]);
const c=companies.find(c=>c.symbol===symbol)||{color:'#335c88',mark:symbol[0]};const upside=data.target&&data.price?(data.target/data.price-1)*100:null;const filtered=watchlist.filter(c=>(c.name+' '+c.symbol).toLowerCase().includes(query.toLowerCase()));const rv=data.volume&&data.averageVolume?data.volume/data.averageVolume:null;
return <main><header className="topbar"><a className="brand" href="#"><Globe2 size={30}/><span>MARKET AFTER HOURS</span></a><nav aria-label="Main navigation">{['dashboard','watchlist','news'].map(n=><button key={n} className={nav===n?'active':''} onClick={()=>{setNav(n);if(window.matchMedia('(max-width:999px)').matches)document.getElementById(n)?.scrollIntoView({behavior:'smooth',block:'start'});else if(n==='watchlist')setSearch(true)}}>{n[0].toUpperCase()+n.slice(1)}</button>)}</nav><div className="header-actions"><button className={`status ${streamStatus==='LIVE STREAM'?'is-live':''}`} onClick={()=>setConnection(true)}><span/>{streamStatus}</button><button className="icon-button" aria-label="Search stocks" onClick={()=>setSearch(true)}><Search size={20}/></button></div></header>
<div className="page-wrap"><section className="masthead" aria-label="Market journal"><div className="mast-copy"><span className="eyebrow">SAME MARKETS.<br/>A BRIGHTER PERSPECTIVE.</span><span className="handwritten">Markets move.<br/><i>So do we.</i></span></div><div className="edition">THE US MARKET EDITION<br/><span>YOUR DAILY INVESTING JOURNAL</span></div></section>
<div className="watchlist-toolbar"><span className="eyebrow">WATCHLIST <b>{watchlist.length}</b></span><div><button aria-label="Previous watchlist page" disabled={watchPage===0} onClick={()=>setWatchPage(p=>p-1)}><ChevronLeft size={15}/></button><span>{watchPage+1} / {Math.ceil(watchlist.length/4)}</span><button aria-label="Next watchlist page" disabled={(watchPage+1)*4>=watchlist.length} onClick={()=>setWatchPage(p=>p+1)}><ChevronRight size={15}/></button><button onClick={()=>setSearch(true)}><Plus size={14}/> Add stock</button></div></div><section className="watchlist" id="watchlist" aria-label="Stock watchlist">{watchlist.slice(watchPage*4,watchPage*4+4).map((co,i)=><div key={co.symbol} className="watch-shell"><button className={`watch-card paper ${co.symbol===symbol?'selected':''}`} aria-pressed={co.symbol===symbol} onClick={()=>setSymbol(co.symbol)}><span className="stock-mark" style={{background:companies.find(c=>c.symbol===co.symbol)?.color||'#335c88'}}>{co.symbol[0]}</span><span className="watch-name"><strong>{co.symbol}</strong><small>{co.name}</small></span>{watchQuotes[co.symbol]?.points?.length>1&&<svg viewBox="0 0 90 35" className="sparkline" aria-hidden="true"><polyline points={watchQuotes[co.symbol].points.map((v,j,arr)=>`${j/(arr.length-1)*90},${32-(v-Math.min(...arr))/(Math.max(...arr)-Math.min(...arr)||1)*28}`).join(' ')} fill="none" stroke={(watchQuotes[co.symbol]?.percent??0)<0?'#ab553d':'#477ee4'} strokeWidth="2"/></svg>}<span className="watch-price"><strong>{co.symbol===symbol?money(data.price):money(watchQuotes[co.symbol]?.price??null)}</strong><small className={(co.symbol===symbol?(data.percent??0):(watchQuotes[co.symbol]?.percent??0))<0?'negative':'positive'}>{co.symbol===symbol&&data.percent!==null?`${data.percent>0?'+':''}${data.percent.toFixed(2)}%`:(watchQuotes[co.symbol]?.percent)!=null?`${(watchQuotes[co.symbol]?.percent)!>0?'+':''}${(watchQuotes[co.symbol]?.percent)!.toFixed(2)}%`:'Awaiting quote'}</small></span></button>{watchlist.length>1&&<button className="remove-stock" aria-label={`Remove ${co.symbol} from watchlist`} onClick={()=>removeStock(co.symbol)}><X size={12}/></button>}</div>)}</section>
{error&&<div className="notice" role="alert">{error} The quote timestamp shows the age of displayed data.</div>}
<div className="dashboard-grid" id="dashboard"><section className="price-panel panel"><div className="stock-heading"><span className="stock-mark large" style={{background:c.color}}>{c.mark}</span><div><div className="title-line"><h1>{symbol}</h1><span className="tag">{data.exchange||'US EQUITY'}</span><span className="tag sector">{data.sector}</span></div><p>{data.name}</p></div><button className={`icon-button refresh ${loading?'spinning':''}`} disabled={loading} onClick={()=>setRefresh(v=>v+1)} aria-label="Refresh stock data"><RefreshCw size={18}/></button></div><div className="price-row"><div className="price-group"><strong className="big-price">{money(data.price)}</strong><span className={(data.percent??0)<0?'negative':'positive'}>{data.percent!==null?`${data.percent>0?'+':''}${data.percent.toFixed(2)}%`:''}<small>{data.change!==null?`${data.change>0?'+':''}${money(data.change)}`:''}</small></span></div><Tabs className="timeframe-control" value={range} onValueChange={setRange}><TabsList aria-label="Chart time range" className="range-tabs">{['1D','1W','1M','3M','1Y'].map(r=><TabsTrigger value={r} key={r}>{r}</TabsTrigger>)}</TabsList></Tabs></div><p className="quote-meta">{data.mode==='demo'?'Waiting for Yahoo Finance':`${usingStream?liveSession+' stream quote':'Latest provider quote'} · ${data.timestamp?new Date(data.timestamp).toLocaleString('en-US',{timeZone:'America/New_York'}):'Time unavailable'} ET`}<span>{stream.connection!=='connected'?`${stream.connection==='connecting'?'Connecting':'Reconnecting'} stream · 60s snapshot fallback`:usingStream?`${tickAge!==null&&tickAge<30?'Receiving updates':'Waiting for next trade'} · Yahoo Finance`:'Stream connected · waiting for first quote'}</span></p><PriceChart data={data} range={range} loading={loading}/></section>
<aside className="brief paper"><div className="section-heading"><h2>Stock brief</h2><Star size={25}/></div><p className="company-description">{data.description}</p><div className="target-grid"><div><span>Analyst target</span><strong>{money(data.target)}</strong><small>{data.targetDate?`Updated ${data.targetDate}`:data.target?'Revision date not supplied':'Not available from provider'}</small></div><div><span>Potential upside</span><strong className={upside!==null&&upside<0?'negative':'positive'}>{upside===null?'—':`${upside>=0?'+':''}${upside.toFixed(1)}%`}</strong><small>vs. current price</small></div></div><p className="fine-print">Analyst consensus, not a guaranteed price. Targets update when research changes.</p></aside>
<section className="earnings panel"><div className="section-heading"><h2><ChartNoAxesCombined size={22}/> Earnings</h2><span className="muted">EPS · USD</span></div><EarningsChart data={data}/><div className="legend"><span><i className="actual"/>Actual</span><span><i className="estimate"/>Estimate</span><small>Calendar quarters · EPS</small></div></section>
<section className="valuation paper"><div className="section-heading"><h2>Valuation</h2><Info size={17}/></div><div className="valuation-row"><span>P/E <small>(TTM)</small></span><strong>{ratio(data.pe)}</strong></div><div className="valuation-row"><span>Forward P/E</span><strong>{ratio(data.forwardPe)}</strong></div><div className="relative-volume"><span>Volume vs. average</span><strong>{rv?`${rv.toFixed(2)}x`:'—'}</strong><small>{rv?'Trading activity, not a buy/sell ratio.':'Volume data unavailable.'}</small></div></section>
<section className="news paper" id="news"><div className="section-heading"><h2><BookOpen size={21}/> News brief</h2><a href={`https://finance.yahoo.com/quote/${symbol}/news/`} target="_blank" rel="noopener noreferrer">All news</a></div><NewsFeed key={symbol} symbol={symbol}/></section></div>
{data.warnings.length>0&&<p className="data-note">{data.warnings.join(' ')}</p>}<footer><span>✦ &nbsp; MARKET AFTER HOURS <b>/</b> THE US MARKET EDITION</span><button onClick={()=>setConnection(true)}><Plug size={14}/>{data.mode==='demo'?'Data connection':'Data connection'}</button><span>{data.mode==='demo'?'WAITING FOR MARKET DATA':'SOURCE: YAHOO FINANCE · CHECK QUOTE TIMESTAMP'}</span></footer></div>
<Dialog open={connection} onOpenChange={setConnection}><DialogContent className="connection-dialog"><DialogTitle>Data connection</DialogTitle><DialogDescription>Source: Yahoo Finance streaming quotes. Prices update when a quote arrives, without waiting for a refresh interval.</DialogDescription><p>Quote timestamps use New York time. The connection automatically reconnects if interrupted, with a 60-second snapshot fallback. An open connection does not guarantee fresh trades; the badge changes when updates stop. Yahoo may delay or omit exchange data.</p><p>The price can include pre-market or after-hours trades; the quote label identifies the session. The chart shows regular-session history. P/E uses trailing earnings; Forward P/E uses estimated earnings. Analyst targets are consensus estimates, refreshed every five minutes, and may not include a revision date.</p><p>Earnings show quarterly actual EPS against analyst estimates. News excerpts come from publisher descriptions; open the original article for full context.</p><a className="source-button" href={`https://finance.yahoo.com/quote/${symbol}/`} target="_blank" rel="noopener noreferrer">Open Yahoo Finance</a></DialogContent></Dialog>
<Dialog open={search} onOpenChange={setSearch}><DialogContent className="connection-dialog"><DialogTitle>Find a stock</DialogTitle><DialogDescription>Search US stocks by symbol or company, then add them to your watchlist.</DialogDescription><input className="search-input" aria-label="Search symbol or company" placeholder="Search symbol or company…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="search-results" aria-live="polite">{searching?<p>Searching Yahoo Finance…</p>:searchError?<p role="alert">{searchError}</p>:query.trim()?searchResults.length?searchResults.map(co=><button key={co.symbol} onClick={()=>addStock(co)}><span><strong>{co.symbol}</strong><small>{co.name} · {co.exchange}</small></span><span>{watchlist.some(c=>c.symbol===co.symbol)?'View':'＋ Add'}</span></button>):<p>No US stocks found. Try a ticker such as AMZN or a company name.</p>:<><p className="search-hint">Your watchlist</p>{filtered.map(co=><button key={co.symbol} onClick={()=>addStock(co)}><strong>{co.symbol}</strong><span>{co.name}</span></button>)}</>}</div></DialogContent></Dialog></main>}
