import {LegalPage} from '@/components/legal/legal-page';
export default function TermsPage(){return <LegalPage title="Terms of service / เงื่อนไขบริการ">
<section><h2>The service / ลักษณะบริการ</h2><p>MOONSTAR provides stock charts, factual price rankings, valuation and earnings data, publisher news links, company relationships and personal watchlists. Screens apply published mathematical filters to available provider data. A rank is not a prediction of future returns or a recommendation tailored to your circumstances.</p><p>ข้อมูลและราคาเป้าหมายจากนักวิเคราะห์ใช้ประกอบการศึกษา ไม่มีการรับประกันกำไรหรือความเหมาะสมกับผู้ใช้แต่ละคน การแสดงข้อความนี้ไม่ทำให้บริการได้รับใบอนุญาตด้านการลงทุนโดยอัตโนมัติ</p></section>
<section><h2>Data limitations / ข้อจำกัดข้อมูล</h2><p>Quotes may be delayed, missing or revised. Stream connectivity and a 15-second refresh are not guarantees of exchange real-time data. Check the source timestamp, trading session, scan coverage and methodology. After-market confirmation uses provider-reported regular-session data, which may differ from exchange-certified closing records. Historical performance does not guarantee future results.</p></section>
<section><h2>Your account / บัญชีของคุณ</h2><p>Keep your sign-in links and browser secure. Use an email address or Google identity that you control. Avoid Remember me on a shared device. Do not bypass access controls, impersonate others or attempt to access another person’s watchlist. You can export your data and request deletion using Account & privacy.</p></section>
<section><h2>Third-party rights / สิทธิ์ของแหล่งข้อมูล</h2><p>Source links and attribution identify providers; they do not grant redistribution rights. Third-party data, news excerpts and logos remain subject to their owners’ terms and rights. A software library license does not license the market data it retrieves. Commercial display and redistribution require appropriate written permissions, including any applicable exchange requirements.</p></section>
<section><h2>Payments and cancellation / การชำระเงิน</h2><p>Planned membership prices are ฿199 per month or ฿1,990 per year, billed at the selected interval and renewing until canceled. Annual billing costs ฿398 less than twelve monthly payments. Checkout is currently disabled and no subscription payments are being collected. Before checkout opens, the final payable amount including any applicable tax, first charge, renewal date, cancellation process and applicable refund terms will be shown for review and explicit authorization. Signing in does not create a paid membership or renewal.</p></section>
<section><h2>Responsibility and complaints / ความรับผิดและข้อร้องเรียน</h2><p>Users remain responsible for investment decisions and should independently verify material information. Nothing here excludes mandatory consumer rights or liability that cannot lawfully be excluded. Report errors, privacy requests or complaints through the operator contact. Applicable jurisdiction and operator details must be settled before commercial launch.</p></section>
</LegalPage>}
