export type ChainStage={id:string;name:string;subtitle:string;phase:number;x:number;y:number;icon:string;companies:string[];description:string;output:string;watch:string;processes?:{name:string;detail:string}[];source:{title:string;url:string;publicationDate?:string;reviewedAt?:string}[]};
const infra={title:'NVIDIA · Infrastructure ecosystem (28 Oct 2025)',publicationDate:'2025-10-28',url:'https://nvidianews.nvidia.com/news/nvidia-partners-ai-infrastructure-america'};
const fab={title:'TSMC · 3DFabric technology',url:'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/3DFabric.htm'};
export const aiStages:ChainStage[]=[
 {id:'materials',name:'Raw materials',subtitle:'Silicon wafers & substrates',phase:0,x:120,y:85,icon:'gem',companies:['4063.T','3436.T'],description:'High-purity silicon is grown into crystals, sliced and polished into wafers. These wafers provide the starting surface on which semiconductor circuits are built.',output:'Polished and epitaxial silicon wafers',watch:'Wafer quality, contamination control and available wafer capacity.',source:[{title:'Shin-Etsu · Silicon wafers',url:'https://www.shinetsu.co.jp/en/products/semiconductor-silicon-business/silicon-wafers/'},{title:'SUMCO · Wafer products',url:'https://www.sumcosi.com/english/products/'}]},
 {id:'equipment',name:'Manufacturing tools',subtitle:'Lithography, etch & inspection',phase:0,x:120,y:210,icon:'factory',companies:['ASML','AMAT','LRCX','KLAC'],description:'Fabrication repeatedly deposits materials, prints patterns, etches structures and measures defects. Lithography is one part of this tightly controlled sequence.',output:'Patterned, deposited and inspected wafer layers',watch:'Tool lead times, process yield, lithography throughput and equipment qualification.',source:[{title:'ASML · Semiconductor technology',url:'https://www.asml.com/en/technology'},{title:'Applied Materials · Semiconductor products',url:'https://www.appliedmaterials.com/us/en/semiconductor.html'},{title:'Lam Research · Products',url:'https://www.lamresearch.com/products/'},{title:'KLA · Products',url:'https://www.kla.com/products'}]},
 {id:'eda',name:'EDA & processor IP',subtitle:'Design, verification & architecture',phase:0,x:120,y:335,icon:'code',companies:['SNPS','CDNS','ARM'],description:'Design software helps engineers implement and verify circuits before fabrication. Reusable processor IP supplies building blocks for custom silicon.',output:'Verified designs, physical layouts and licensed IP',watch:'Verification complexity, design closure and compatibility with foundry processes.',source:[{title:'Synopsys · AI design tools',url:'https://www.synopsys.com/ai.html'},{title:'Cadence · AI',url:'https://www.cadence.com/en_US/home/solutions/artificial-intelligence.html'},{title:'Arm · Cloud-to-edge architecture',url:'https://newsroom.arm.com/blog/from-cloud-to-edge-arm-scales-your-ai-stack'}]},
 {id:'design',name:'Chip design',subtitle:'GPUs, CPUs & custom accelerators',phase:1,x:360,y:85,icon:'chip',companies:['NVDA','AMD','AVGO','MRVL'],description:'Designers define the compute architecture, memory interfaces and interconnects. GPU platforms and custom accelerators represent different approaches; companies listed here are not all suppliers to one another.',output:'Accelerator and processor designs for manufacturing',watch:'Performance per watt, software support, tape-out schedules and design execution.',source:[{title:'NVIDIA · Blackwell platform',url:'https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing'},{title:'AMD · Instinct accelerators',url:'https://www.amd.com/en/products/accelerators/instinct.html'},{title:'NVIDIA & Marvell · NVLink Fusion',url:'https://nvidianews.nvidia.com/news/nvidia-ai-ecosystem-expands-as-marvell-joins-forces-through-nvlink-fusion'}]},
 {id:'foundry',name:'Foundries',subtitle:'Leading-edge wafer fabrication',phase:1,x:360,y:210,icon:'factory',companies:['TSM','INTC','005930.KS'],description:'Foundries turn chip layouts into physical logic dies. TSMC manufactures Blackwell; Intel Foundry and Samsung Foundry are other industry participants, not implied Blackwell manufacturers.',output:'Fabricated logic dies',watch:'Process-node capacity, yields and qualification of new manufacturing processes.',source:[{title:'NVIDIA · Blackwell manufacturing',url:'https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing'},{title:'Intel · Foundry',url:'https://www.intel.com/content/www/us/en/foundry/overview.html'},{title:'Samsung · Foundry',url:'https://semiconductor.samsung.com/foundry/'}]},
 {id:'memory',name:'Memory / HBM',subtitle:'Stacked DRAM beside the accelerator',phase:1,x:360,y:335,icon:'memory',companies:['MU','000660.KS','005930.KS'],description:'High-bandwidth memory stacks DRAM dies to feed accelerators with data. Memory is integrated with logic through advanced packaging rather than functioning as a standalone compute device.',output:'HBM stacks and supporting server memory',watch:'Stack yields, thermal performance, qualified supply and bandwidth per accelerator.',source:[{title:'Micron · HBM portfolio',url:'https://www.micron.com/products/memory/hbm'},{title:'NVIDIA & SK hynix · Memory partnership',url:'https://nvidianews.nvidia.com/news/sk-hynix-ai-factory'},{title:'Samsung · HBM',url:'https://semiconductor.samsung.com/dram/hbm/'}]},
 {id:'optics',name:'Photonics & optics',subtitle:'Lasers, transceivers & optical links',phase:2,x:600,y:85,icon:'cable',companies:['COHR','LITE'],description:'Optical links carry data between switches and systems. Co-packaged optics brings optical engines close to switch silicon, with lasers, fiber coupling and packaging all contributing to reliability.',output:'High-speed optical connectivity',watch:'Optical alignment, laser reliability, manufacturing yield and power per transmitted bit.',source:[{title:'NVIDIA · Co-packaged optics',url:'https://developer.nvidia.com/blog/how-industry-collaboration-fosters-nvidia-co-packaged-optics/'},{title:'NVIDIA & Lumentum · Optics partnership',url:'https://nvidianews.nvidia.com/news/nvidia-announces-strategic-partnership-with-lumentum-to-develop-state-of-the-art-optics-technology'},{title:'NVIDIA · Coherent and infrastructure',url:'https://blogs.nvidia.com/blog/nvidia-and-partners-build-in-america-for-america/'}]},
 {id:'packaging',name:'Packaging & test',subtitle:'CoWoS, chiplets & heterogeneous integration',phase:2,x:600,y:210,icon:'layers',companies:['TSM','ASX','AMKR'],description:'Advanced packaging connects logic, memory and other dies into a working module. Foundry packaging and outsourced assembly/test services serve different parts of this process.',output:'Packaged and tested accelerator modules',watch:'Interposer and substrate capacity, assembly yield and test throughput.',source:[fab,{title:'ASE · Advanced packaging (26 May 2026)',publicationDate:'2026-05-26',url:'https://ase.aseglobal.com/press-room/310x310/'},{title:'Amkor · AI packaging',url:'https://amkor.com/applications/artificial-intelligence/'}]},
 {id:'network',name:'Networking silicon',subtitle:'Switches, NICs & scale-out fabrics',phase:2,x:600,y:335,icon:'network',companies:['NVDA','AVGO','MRVL','ANET','CSCO'],description:'Network fabrics coordinate many accelerators across racks. Switch silicon, network adapters and complete switching systems are distinct product layers.',output:'Connected accelerator clusters',watch:'Congestion, latency, network bandwidth and interoperability at cluster scale.',source:[{title:'Arista · AI networking',url:'https://www.arista.com/en/solutions/ai-networking'},{title:'Arista & Broadcom · AI fabrics (9 Jun 2026)',publicationDate:'2026-06-09',url:'https://www.arista.com/company/news/press-release/24102-pr-20260609'},infra]},
 {id:'servers',name:'Servers & racks',subtitle:'System assembly and integration',phase:3,x:840,y:210,icon:'server',companies:['DELL','HPE','SMCI','2317.TW'],description:'System builders integrate accelerators, CPUs, memory, network adapters and cooling into servers and racks, then validate the complete system.',output:'Deployable AI servers and rack-scale systems',watch:'Component synchronization, rack validation, assembly capacity and deployment schedules.',source:[infra,{title:'NVIDIA · Manufacturing partners',url:'https://blogs.nvidia.com/blog/nvidia-and-partners-build-in-america-for-america/'}]},
 {id:'power',name:'Power & thermal',subtitle:'Electricity distribution and cooling',phase:3,x:840,y:335,icon:'power',companies:['VRT','ETN','SU.PA','GEV','TT'],description:'Electrical and cooling systems make high-density AI infrastructure operable. Power conversion, distribution, backup and heat removal must be engineered together.',output:'Powered and cooled compute capacity',watch:'Grid connection schedules, power availability and liquid-cooling readiness. Watchpoints are not live shortage measurements.',source:[infra]},
 {id:'cloud',name:'Hyperscalers & clouds',subtitle:'Training and inference deployment',phase:4,x:1080,y:85,icon:'cloud',companies:['MSFT','AMZN','GOOGL','ORCL','META','CRWV'],description:'Cloud providers turn infrastructure into compute services; Meta also deploys infrastructure for its own platforms. These are different business models within the deployment layer.',output:'Training clusters and inference services',watch:'Data-center readiness, utilization, customer demand and capital spending.',source:[{title:'NVIDIA · Blackwell cloud ecosystem',url:'https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing'},infra]},
 {id:'storage',name:'AI storage & data',subtitle:'Training data, checkpoints & context',phase:4,x:1080,y:335,icon:'database',companies:['NTAP','P','IBM','VAST','DELL','HPE','6501.T','NTNX','DDN_PRIVATE','WEKA_PRIVATE','CLOUDIAN_PRIVATE','MINIO_PRIVATE'],description:'Storage platforms keep data accessible for training and inference. Performance depends on moving data to compute quickly, not just total storage capacity.',output:'Data pipelines, model checkpoints and persistent context',watch:'Data throughput, metadata performance and integration with compute clusters.',source:[{"title": "NVIDIA · STX storage ecosystem", "url": "https://nvidianews.nvidia.com/news/nvidia-launches-bluefield-4-stx-storage-architecture-with-broad-industry-adoption", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}]},
 {id:'datacenters',name:'Data-center operators',subtitle:'Colocation, buildings & interconnection',phase:3,x:840,y:85,icon:'factory',companies:['EQIX','DLR'],description:'Data-center operators provide physical sites, power-ready space and connectivity. Colocation is distinct from selling GPU compute instances. These operators can support AI workloads without being an exclusive supplier to a chip designer.',output:'Connected, power-ready facilities for compute deployments',watch:'Available megawatts, utility connections, construction delivery and customer commitments.',source:[{title:'Equinix · AI infrastructure',url:'https://www.equinix.com/product-solutions/ai',reviewedAt:'2026-10-10'},{title:'Digital Realty · Investor presentation',url:'https://investor.digitalrealty.com/static-files/36e0f946-fd91-48b6-9ce2-86463d92496b',reviewedAt:'2026-10-10'}]},
 {id:'software',name:'AI software & runtime',subtitle:'Libraries, serving & orchestration',phase:5,x:1320,y:85,icon:'code',companies:['MSFT','NVDA','GOOGL','AMZN','IBM'],description:'Software connects hardware to usable AI: accelerator libraries, distributed training, model serving and workload orchestration. NVIDIA AI Enterprise includes optimized inference components; cloud platforms also expose managed AI services. Inclusion is an industry role, not a direct purchasing contract.',output:'Training and inference execution environments',watch:'Hardware portability, software compatibility, serving latency, utilization and operational security.',source:[{title:'NVIDIA · AI Enterprise application software',url:'https://docs.nvidia.com/ai-enterprise/software/latest/application-software.html',reviewedAt:'2026-10-10'},{title:'Microsoft · Foundry',url:'https://learn.microsoft.com/en-us/azure/foundry/',reviewedAt:'2026-10-10'},{title:'AWS · SageMaker',url:'https://aws.amazon.com/sagemaker/',reviewedAt:'2026-10-10'},{title:'Google · Gemini platform',url:'https://cloud.google.com/vertex-ai',reviewedAt:'2026-10-10'},{title:'IBM · watsonx',url:'https://www.ibm.com/watsonx',reviewedAt:'2026-10-10'}]},
 {id:'models',name:'Models & research',subtitle:'Pretraining, fine-tuning & evaluation',phase:5,x:1320,y:210,icon:'chip',companies:['GOOGL','META','OPENAI_PRIVATE','ANTHROPIC_PRIVATE'],description:'Model developers train, evaluate and distribute foundation models. Models may be offered through APIs or released with specific licenses. Private model providers are retained in this map without fictional stock tickers or public market capitalization.',output:'Model weights, inference APIs and evaluated capabilities',watch:'Training data rights, evaluation quality, inference costs, model licenses and availability.',source:[{title:'Google DeepMind · Models',url:'https://deepmind.google/models/',reviewedAt:'2026-10-10'},{title:'Meta · Llama',url:'https://www.llama.com/',reviewedAt:'2026-10-10'},{title:'OpenAI · Model catalog',url:'https://developers.openai.com/api/docs/models',reviewedAt:'2026-10-10'},{title:'Anthropic · Company',url:'https://www.anthropic.com/company',reviewedAt:'2026-10-10'}]},
 {id:'applications',name:'AI apps & agents',subtitle:'Business workflows & user products',phase:5,x:1320,y:335,icon:'cloud',companies:['MSFT','CRM','GOOGL','NOW'],description:'Application providers turn model capabilities into user workflows: assistants, customer service, search and enterprise automation. Revenue and market capitalization here belong to the whole company, not only its AI products.',output:'User-facing assistants and business automation',watch:'Adoption, measurable workflow outcomes, permissions, privacy and human oversight.',source:[{title:'Microsoft · Copilot',url:'https://www.microsoft.com/en-us/microsoft-copilot',reviewedAt:'2026-10-10'},{title:'Salesforce · Agentforce',url:'https://www.salesforce.com/agentforce/',reviewedAt:'2026-10-10'},{title:'Google · Gemini',url:'https://gemini.google/about/',reviewedAt:'2026-10-10'},{title:'ServiceNow · Now Assist',url:'https://www.servicenow.com/docs/r/intelligent-experiences/platform-now-assist-landing.html',reviewedAt:'2026-10-10'}]},

{"id": "finance", "name": "Capital & financing", "subtitle": "Funding long-lived infrastructure", "phase": 0, "x": 120, "y": 460, "icon": "layers", "companies": ["APO", "BLK", "BX", "BAM", "GS", "KKR"], "description": "Financing supports infrastructure buildout. Named firms announced financing-platform plans; this does not establish completed funding or supplier contracts.", "output": "Capital structures for infrastructure projects", "watch": "Final agreements, financing costs and project execution.", "source": [{"title": "NVIDIA · Announced infrastructure financing platforms", "url": "https://nvidianews.nvidia.com/news/nvidia-partners-with-apollo-blackrock-blackstone-brookfield-goldman-sachs-and-kkr-to-establish-ai-compute-infrastructure-financing-platforms-to-mobilize-over-500-billion-of-third-party-capital", "publicationDate": "2026-08-10", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Underwriting", "detail": "Assess counterparty and asset risks."}, {"name": "Capital structure", "detail": "Match financing to project cash flows."}, {"name": "Deployment", "detail": "Track actual funded projects separately from announcements."}]},

{"id": "energy", "name": "Energy & grid", "subtitle": "Generation, storage & connections", "phase": 0, "x": 120, "y": 585, "icon": "power", "companies": ["AES", "CEG", "NEE", "VST", "INVENERGY_PRIVATE", "EMERALD_PRIVATE", "GEV", "ENR.DE", "6501.T"], "description": "Energy providers and grid technology enable compute capacity. Announced collaborations may include future projects rather than operating capacity.", "output": "Power availability and grid coordination", "watch": "Permits, connection queues and resource reliability.", "source": [{"title": "NVIDIA · Energy and grid collaboration", "url": "https://nvidianews.nvidia.com/news/nvidia-and-emerald-ai-join-leading-energy-companies-to-pioneer-flexible-ai-factories-as-grid-assets", "publicationDate": "2026-03-23", "reviewedAt": "2026-10-10"}, {"title": "NVIDIA · AI factory design ecosystem", "url": "https://nvidianews.nvidia.com/news/nvidia-releases-vera-rubin-dsx-ai-factory-reference-design-and-omniverse-dsx-digital-twin-blueprint-with-broad-industry-support", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Generation", "detail": "Plan generation and storage resources."}, {"name": "Grid connection", "detail": "Coordinate utilities and interconnection."}, {"name": "Flexible demand", "detail": "Align compute demand with power constraints."}]},

{"id": "construction", "name": "Engineering & buildout", "subtitle": "Sites, construction & digital twins", "phase": 3, "x": 840, "y": 460, "icon": "factory", "companies": ["J", "PCOR", "PTC", "DSY.PA", "SIE.DE", "CDNS"], "description": "Engineering software and construction workflows support facility delivery. Industry participation is distinct from equipment supply.", "output": "Facility designs and coordinated construction", "watch": "Schedule, permits and delivery risk.", "source": [{"title": "NVIDIA · AI factory design ecosystem", "url": "https://nvidianews.nvidia.com/news/nvidia-releases-vera-rubin-dsx-ai-factory-reference-design-and-omniverse-dsx-digital-twin-blueprint-with-broad-industry-support", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Design", "detail": "Model site and facility requirements."}, {"name": "Construction", "detail": "Coordinate plans and field execution."}, {"name": "Commissioning", "detail": "Validate the completed facility before operations."}]},

{"id": "operations", "name": "Facility control", "subtitle": "Monitoring, cooling & optimization", "phase": 3, "x": 840, "y": 585, "icon": "network", "companies": ["PHAIDRA_PRIVATE", "SWITCH_PRIVATE", "ETN", "SU.PA", "TT", "VRT"], "description": "Control software links compute operation with electrical and thermal systems. Monitoring is distinct from selling hardware.", "output": "Operational control of facility resources", "watch": "Reliability, system integration and control boundaries.", "source": [{"title": "NVIDIA · AI factory design ecosystem", "url": "https://nvidianews.nvidia.com/news/nvidia-releases-vera-rubin-dsx-ai-factory-reference-design-and-omniverse-dsx-digital-twin-blueprint-with-broad-industry-support", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Telemetry", "detail": "Measure infrastructure state."}, {"name": "Control", "detail": "Coordinate equipment and workload constraints."}, {"name": "Maintenance", "detail": "Inspect and maintain operational systems."}]},

{"id": "dataplatforms", "name": "Data platforms & retrieval", "subtitle": "Enterprise data, embeddings & context", "phase": 4, "x": 1080, "y": 210, "icon": "database", "companies": ["SNOW", "MSFT", "AMZN", "GOOGL", "IBM", "BOX"], "description": "Data platforms organize enterprise information for AI workflows. Retrieval must respect the same access rights as the underlying data.", "output": "Governed information and retrieval context", "watch": "Data quality, access control and region availability.", "source": [{"title": "Snowflake · Cortex AI functions", "url": "https://docs.snowflake.com/en/user-guide/snowflake-cortex/aisql", "reviewedAt": "2026-10-10"}, {"title": "NVIDIA · Agent platform ecosystem", "url": "https://nvidianews.nvidia.com/news/ai-agents", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Ingestion", "detail": "Load and normalize approved source data."}, {"name": "Retrieval", "detail": "Select relevant information for inference."}, {"name": "Governance", "detail": "Retain provenance and enforce permissions."}]},

{"id": "datasets", "name": "Datasets & evaluation", "subtitle": "Curation, annotation & quality checks", "phase": 4, "x": 1080, "y": 460, "icon": "layers", "companies": ["HUGGINGFACE_PRIVATE", "SCALE_PRIVATE", "NVDA"], "description": "Dataset hosting, curation and evaluation enable model development. Dataset availability does not itself grant rights for every training use.", "output": "Documented datasets and evaluation inputs", "watch": "Licenses, provenance, privacy and representative coverage.", "source": [{"title": "Hugging Face · Dataset documentation", "url": "https://huggingface.co/docs/hub/en/datasets", "reviewedAt": "2026-10-10"}, {"title": "NVIDIA · Open Agent Safety ecosystem", "url": "https://nvidianews.nvidia.com/news/open-agent-safety-platform", "publicationDate": "2026-09-28", "reviewedAt": "2026-10-10"}, {"title": "NVIDIA · Physical AI ecosystem", "url": "https://nvidianews.nvidia.com/news/nvidia-and-global-robotics-leaders-take-physical-ai-to-the-real-world", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Provenance", "detail": "Record origins and permitted uses."}, {"name": "Preparation", "detail": "Clean, annotate or generate training inputs."}, {"name": "Evaluation", "detail": "Measure model behavior on independent examples."}]},

{"id": "inference", "name": "Inference providers", "subtitle": "Managed model serving & APIs", "phase": 4, "x": 1080, "y": 585, "icon": "cloud", "companies": ["CRWV", "DOCN", "BASETEN_PRIVATE", "FIREWORKS_PRIVATE", "TOGETHER_PRIVATE", "VULTR_PRIVATE"], "description": "Specialist providers expose model-serving capacity alongside general-purpose clouds. Service availability and performance vary by provider.", "output": "Hosted inference endpoints", "watch": "Latency, uptime and unit economics.", "source": [{"title": "NVIDIA · Agent platform ecosystem", "url": "https://nvidianews.nvidia.com/news/ai-agents", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}, {"title": "NVIDIA · Open Agent Safety ecosystem", "url": "https://nvidianews.nvidia.com/news/open-agent-safety-platform", "publicationDate": "2026-09-28", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Deployment", "detail": "Package and load model versions."}, {"name": "Serving", "detail": "Route requests and manage capacity."}, {"name": "Monitoring", "detail": "Measure errors, latency and cost."}]},

{"id": "devtools", "name": "Agent development", "subtitle": "Frameworks, tools & evaluation", "phase": 5, "x": 1320, "y": 460, "icon": "code", "companies": ["LANGCHAIN_PRIVATE", "NVDA", "MSFT", "GOOGL", "IBM"], "description": "Development frameworks connect models, tools and state into applications. Tool access requires explicit authorization.", "output": "Agent orchestration and development workflows", "watch": "Evaluation quality, tool permissions and reproducibility.", "source": [{"title": "NVIDIA · Agent platform ecosystem", "url": "https://nvidianews.nvidia.com/news/ai-agents", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Orchestration", "detail": "Coordinate models, tools and state."}, {"name": "Evaluation", "detail": "Test task outcomes and failure modes."}, {"name": "Observability", "detail": "Inspect execution traces and incidents."}]},

{"id": "safety", "name": "AI security & governance", "subtitle": "Isolation, policy & human oversight", "phase": 5, "x": 1320, "y": 585, "icon": "network", "companies": ["CRWD", "PANW", "CSCO", "MSFT", "NVDA", "ANTHROPIC_PRIVATE", "SCALE_PRIVATE"], "description": "Security providers and model developers contribute controls for AI deployments. Participation is not a certification that a product is safe.", "output": "Controlled and auditable AI execution", "watch": "Identity, data boundaries and incident response.", "source": [{"title": "NVIDIA · Open Agent Safety ecosystem", "url": "https://nvidianews.nvidia.com/news/open-agent-safety-platform", "publicationDate": "2026-09-28", "reviewedAt": "2026-10-10"}, {"title": "NVIDIA · Agent platform ecosystem", "url": "https://nvidianews.nvidia.com/news/ai-agents", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Isolation", "detail": "Limit execution and network access."}, {"name": "Policy", "detail": "Enforce permissions outside model reasoning."}, {"name": "Audit", "detail": "Record events and support human intervention."}]},

{"id": "simulation", "name": "Simulation & spatial AI", "subtitle": "Digital worlds for design & training", "phase": 6, "x": 1560, "y": 85, "icon": "layers", "companies": ["NVDA", "DSY.PA", "SIE.DE", "PTC", "CDNS", "WORLDLABS_PRIVATE"], "description": "Simulation provides virtual environments for engineering and AI development. Virtual testing does not replace validation in operating conditions.", "output": "Digital environments and simulated training inputs", "watch": "Model fidelity and the gap between simulation and reality.", "source": [{"title": "NVIDIA · AI factory design ecosystem", "url": "https://nvidianews.nvidia.com/news/nvidia-releases-vera-rubin-dsx-ai-factory-reference-design-and-omniverse-dsx-digital-twin-blueprint-with-broad-industry-support", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}, {"title": "NVIDIA · Physical AI ecosystem", "url": "https://nvidianews.nvidia.com/news/nvidia-and-global-robotics-leaders-take-physical-ai-to-the-real-world", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Modeling", "detail": "Represent environments and system behavior."}, {"name": "Training", "detail": "Create scenarios and synthetic observations."}, {"name": "Validation", "detail": "Compare simulation with measured outcomes."}]},

{"id": "physical", "name": "Robotics & physical AI", "subtitle": "Industrial, humanoid & medical systems", "phase": 6, "x": 1560, "y": 210, "icon": "factory", "companies": ["6954.T", "6506.T", "MDT", "FIGURE_PRIVATE", "SKILD_PRIVATE", "NVDA"], "description": "Physical AI combines models, sensors and control with machines. Industrial, humanoid and medical systems have different deployment requirements.", "output": "Machines acting in physical environments", "watch": "Safety validation and real-world reliability.", "source": [{"title": "NVIDIA · Physical AI ecosystem", "url": "https://nvidianews.nvidia.com/news/nvidia-and-global-robotics-leaders-take-physical-ai-to-the-real-world", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}, {"title": "NVIDIA · Open Agent Safety ecosystem", "url": "https://nvidianews.nvidia.com/news/open-agent-safety-platform", "publicationDate": "2026-09-28", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Perception", "detail": "Interpret sensor observations."}, {"name": "Planning", "detail": "Choose actions under operational constraints."}, {"name": "Control", "detail": "Execute and validate physical actions."}]},

{"id": "enterprise", "name": "Industry applications", "subtitle": "Creative, telecom & life sciences", "phase": 6, "x": 1560, "y": 335, "icon": "cloud", "companies": ["ADBE", "TEAM", "DOX", "BOX", "IQV", "SAP", "PLTR", "CRM", "NOW"], "description": "Application companies adapt AI to domain workflows. Industry membership does not imply equivalent functionality or revenue exposure.", "output": "Domain-specific AI workflows", "watch": "Customer adoption and verified task outcomes.", "source": [{"title": "NVIDIA · Agent platform ecosystem", "url": "https://nvidianews.nvidia.com/news/ai-agents", "publicationDate": "2026-03-16", "reviewedAt": "2026-10-10"}, {"title": "NVIDIA · Open Agent Safety ecosystem", "url": "https://nvidianews.nvidia.com/news/open-agent-safety-platform", "publicationDate": "2026-09-28", "reviewedAt": "2026-10-10"}], "processes": [{"name": "Integration", "detail": "Connect approved domain systems."}, {"name": "Deployment", "detail": "Validate workflows with users."}, {"name": "Oversight", "detail": "Monitor outcomes and escalation paths."}]}
];
export const aiFlows=[
 ['materials','foundry','Wafers'],['equipment','foundry','Process tools'],['eda','design','Design & IP'],['design','foundry','Tape-out'],['foundry','packaging','Logic dies'],['memory','packaging','HBM stacks'],['packaging','servers','Modules'],['optics','servers','Optical links'],['network','servers','Cluster fabric'],['power','servers','Power & cooling'],['servers','cloud','Compute capacity'],['storage','cloud','Data services'],['servers','storage','Storage systems'],['datacenters','servers','Facilities & connectivity'],['cloud','software','Hosted compute'],['storage','software','Accessible data'],['software','models','Training & serving'],['models','applications','Model capabilities'],
["finance", "construction", "Project capital"],["energy", "power", "Energy resources"],["construction", "datacenters", "Facility delivery"],["operations", "power", "Facility controls"],["datacenters", "operations", "Operational telemetry"],["dataplatforms", "models", "Training inputs"],["datasets", "models", "Evaluation and datasets"],["storage", "dataplatforms", "Persistent data"],["models", "inference", "Deployable models"],["cloud", "inference", "Compute resources"],["inference", "applications", "Model APIs"],["devtools", "applications", "Agent tooling"],["safety", "applications", "Security controls"],["dataplatforms", "applications", "Retrieval context"],["models", "simulation", "Model capabilities"],["simulation", "physical", "Virtual training"],["models", "physical", "Robot intelligence"],["applications", "enterprise", "Domain workflows"],["safety", "physical", "Safety controls"],
].map(([from,to,label])=>({from,to,label}));
export const phaseNames=['Foundations','Silicon & memory','Integration','Infrastructure','Deployment','Software & intelligence','Real-world applications'];
export function stagesFor(symbol:string){return aiStages.filter(s=>s.companies.includes(symbol==='GOOG'?'GOOGL':symbol==='PSTG'?'P':symbol))}

// Process breakdowns explain the industry flow; they do not assert issuer contracts.
const breakdowns:Record<string,[string,string][]>= {
 materials:[['Crystal growth','Purify silicon and grow single-crystal ingots.'],['Wafer preparation','Slice, polish and inspect wafers; epitaxial layers suit selected processes.'],['Substrate qualification','Control defects and contamination before fab processing.']],
 equipment:[['Lithography','Pattern wafer layers with exposure systems and computational correction.'],['Deposition & etch','Add thin films and selectively remove material to build structures.'],['Metrology & inspection','Measure overlay, dimensions and defects to control yield.']],
 eda:[['Architecture & IP','Select processor interfaces and licensed building blocks.'],['Implementation & verification','Simulate, verify and place-and-route circuit designs.'],['Sign-off','Check timing, power, physical rules and foundry compatibility.']],
 design:[['Compute architecture','Develop GPUs, CPUs and custom accelerator execution units.'],['Memory & interconnect','Design interfaces, caches and communication fabrics.'],['Tape-out','Release a validated physical design to the fab.']],
 foundry:[['Front-end processing','Pattern transistors and device structures over many repeated steps.'],['Interconnect layers','Build metal wiring and dielectric layers connecting devices.'],['Wafer probe','Test dies before assembly and identify usable components.']],
 memory:[['DRAM fabrication','Manufacture the memory dies.'],['Stacking & TSVs','Stack dies with vertical connections for high bandwidth.'],['Qualification','Validate bandwidth, power and thermal behavior with accelerator platforms.']],
 optics:[['Light sources','Generate optical signals with laser components.'],['Transceivers & coupling','Convert electrical/optical signals and connect fiber.'],['System integration','Validate link integrity, power and optical packaging.']],
 packaging:[['Interposers & substrates','Route connections between logic and memory dies.'],['Assembly','Integrate chiplets and HBM into modules.'],['Test & reliability','Check functionality, thermals and manufacturing yield.']],
 network:[['Switch silicon & NICs','Move data between accelerators and hosts.'],['Switch systems','Combine silicon with software and physical interfaces.'],['Cluster fabric','Engineer topology, congestion control and interoperability.']],
 servers:[['System integration','Combine compute, memory, storage and networking.'],['Rack assembly','Integrate power distribution, cabling and cooling interfaces.'],['Validation','Test complete systems before deployment.']],
 power:[['Power distribution','Convert and distribute facility power to racks.'],['Backup & resilience','Plan redundant electrical infrastructure and recovery.'],['Heat removal','Match air or liquid cooling to rack density and site conditions.']],
 cloud:[['Capacity deployment','Install and operate clusters in ready facilities.'],['Compute services','Expose instances, managed training or inference services.'],['Operations','Monitor utilization, reliability and customer demand.']],
 storage:[['Data ingestion','Prepare and persist source datasets.'],['Training I/O','Deliver data and save checkpoints efficiently.'],['Inference context','Supply retrieval and persistent application data.']],
 datacenters:[['Site & utility planning','Secure locations, power and network access.'],['Facility delivery','Build resilient electrical and cooling infrastructure.'],['Colocation & interconnection','Host customer hardware and connect service providers.']],
 software:[['Acceleration libraries','Provide device kernels, communication and framework integration.'],['Training orchestration','Schedule distributed jobs and manage checkpoints.'],['Inference serving','Deploy models with batching, caching and monitoring.']],
 models:[['Data preparation','Curate licensed datasets and training objectives.'],['Training & adaptation','Pretrain and adapt models for target tasks.'],['Evaluation & release','Evaluate quality and publish models or APIs under stated terms.']],
 applications:[['Workflow integration','Connect models with approved business data and tools.'],['Access & controls','Enforce permissions, privacy and user oversight.'],['Product outcomes','Measure quality and usefulness in deployed workflows.']],
};
for(const stage of aiStages)stage.processes=stage.processes||(breakdowns[stage.id]||[]).map(([name,detail])=>({name,detail}));
export const summaryAiStages=aiStages.slice(0,17).map(stage=>stage.id==='storage'?{...stage,companies:stage.companies.slice(0,4)}:stage);
export const summaryAiFlows=aiFlows.filter(edge=>summaryAiStages.some(s=>s.id===edge.from)&&summaryAiStages.some(s=>s.id===edge.to));
export function industryEvidenceDates(stages:ChainStage[]=aiStages){const sources=stages.flatMap(s=>s.source);const dates=sources.flatMap(s=>s.publicationDate?[s.publicationDate]:[]).sort();return {latestPublication:dates.at(-1)||null,lastReviewed:sources.flatMap(s=>s.reviewedAt?[s.reviewedAt]:[]).sort().at(-1)||null,undatedSources:sources.filter(s=>!s.publicationDate).length};}
