export type ChainStage={id:string;name:string;subtitle:string;phase:number;x:number;y:number;icon:string;companies:string[];description:string;output:string;watch:string;source:{title:string;url:string}[]};
const infra={title:'NVIDIA · Infrastructure ecosystem (28 Oct 2025)',url:'https://nvidianews.nvidia.com/news/nvidia-partners-ai-infrastructure-america'};
const fab={title:'TSMC · 3DFabric technology',url:'https://3dfabric.tsmc.com/english/dedicatedFoundry/technology/3DFabric.htm'};
export const aiStages:ChainStage[]=[
 {id:'materials',name:'Raw materials',subtitle:'Silicon wafers & substrates',phase:0,x:120,y:85,icon:'gem',companies:['4063.T','3436.T'],description:'High-purity silicon is grown into crystals, sliced and polished into wafers. These wafers provide the starting surface on which semiconductor circuits are built.',output:'Polished and epitaxial silicon wafers',watch:'Wafer quality, contamination control and available wafer capacity.',source:[{title:'Shin-Etsu · Silicon wafers',url:'https://www.shinetsu.co.jp/en/products/semiconductor-silicon-business/silicon-wafers/'},{title:'SUMCO · Wafer products',url:'https://www.sumcosi.com/english/products/'}]},
 {id:'equipment',name:'Manufacturing tools',subtitle:'Lithography, etch & inspection',phase:0,x:120,y:210,icon:'factory',companies:['ASML','AMAT','LRCX','KLAC'],description:'Fabrication repeatedly deposits materials, prints patterns, etches structures and measures defects. Lithography is one part of this tightly controlled sequence.',output:'Patterned, deposited and inspected wafer layers',watch:'Tool lead times, process yield, lithography throughput and equipment qualification.',source:[{title:'ASML · Semiconductor technology',url:'https://www.asml.com/en/technology'},{title:'Applied Materials · Semiconductor products',url:'https://www.appliedmaterials.com/us/en/semiconductor.html'},{title:'Lam Research · Products',url:'https://www.lamresearch.com/products/'},{title:'KLA · Products',url:'https://www.kla.com/products'}]},
 {id:'eda',name:'EDA & processor IP',subtitle:'Design, verification & architecture',phase:0,x:120,y:335,icon:'code',companies:['SNPS','CDNS','ARM'],description:'Design software helps engineers implement and verify circuits before fabrication. Reusable processor IP supplies building blocks for custom silicon.',output:'Verified designs, physical layouts and licensed IP',watch:'Verification complexity, design closure and compatibility with foundry processes.',source:[{title:'Synopsys · AI design tools',url:'https://www.synopsys.com/ai.html'},{title:'Cadence · AI',url:'https://www.cadence.com/en_US/home/solutions/artificial-intelligence.html'},{title:'Arm · Cloud-to-edge architecture',url:'https://newsroom.arm.com/blog/from-cloud-to-edge-arm-scales-your-ai-stack'}]},
 {id:'design',name:'Chip design',subtitle:'GPUs, CPUs & custom accelerators',phase:1,x:360,y:85,icon:'chip',companies:['NVDA','AMD','AVGO','MRVL'],description:'Designers define the compute architecture, memory interfaces and interconnects. GPU platforms and custom accelerators represent different approaches; companies listed here are not all suppliers to one another.',output:'Accelerator and processor designs for manufacturing',watch:'Performance per watt, software support, tape-out schedules and design execution.',source:[{title:'NVIDIA · Blackwell platform',url:'https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing'},{title:'AMD · Instinct accelerators',url:'https://www.amd.com/en/products/accelerators/instinct.html'},{title:'NVIDIA & Marvell · NVLink Fusion',url:'https://nvidianews.nvidia.com/news/nvidia-ai-ecosystem-expands-as-marvell-joins-forces-through-nvlink-fusion'}]},
 {id:'foundry',name:'Foundries',subtitle:'Leading-edge wafer fabrication',phase:1,x:360,y:210,icon:'factory',companies:['TSM','INTC','005930.KS'],description:'Foundries turn chip layouts into physical logic dies. TSMC manufactures Blackwell; Intel Foundry and Samsung Foundry are other industry participants, not implied Blackwell manufacturers.',output:'Fabricated logic dies',watch:'Process-node capacity, yields and qualification of new manufacturing processes.',source:[{title:'NVIDIA · Blackwell manufacturing',url:'https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing'},{title:'Intel · Foundry',url:'https://www.intel.com/content/www/us/en/foundry/overview.html'},{title:'Samsung · Foundry',url:'https://semiconductor.samsung.com/foundry/'}]},
 {id:'memory',name:'Memory / HBM',subtitle:'Stacked DRAM beside the accelerator',phase:1,x:360,y:335,icon:'memory',companies:['MU','000660.KS','005930.KS'],description:'High-bandwidth memory stacks DRAM dies to feed accelerators with data. Memory is integrated with logic through advanced packaging rather than functioning as a standalone compute device.',output:'HBM stacks and supporting server memory',watch:'Stack yields, thermal performance, qualified supply and bandwidth per accelerator.',source:[{title:'Micron · HBM portfolio',url:'https://www.micron.com/products/memory/hbm'},{title:'NVIDIA & SK hynix · Memory partnership',url:'https://nvidianews.nvidia.com/news/sk-hynix-ai-factory'},{title:'Samsung · HBM',url:'https://semiconductor.samsung.com/dram/hbm/'}]},
 {id:'optics',name:'Photonics & optics',subtitle:'Lasers, transceivers & optical links',phase:2,x:600,y:85,icon:'cable',companies:['COHR','LITE'],description:'Optical links carry data between switches and systems. Co-packaged optics brings optical engines close to switch silicon, with lasers, fiber coupling and packaging all contributing to reliability.',output:'High-speed optical connectivity',watch:'Optical alignment, laser reliability, manufacturing yield and power per transmitted bit.',source:[{title:'NVIDIA · Co-packaged optics',url:'https://developer.nvidia.com/blog/how-industry-collaboration-fosters-nvidia-co-packaged-optics/'},{title:'NVIDIA & Lumentum · Optics partnership',url:'https://nvidianews.nvidia.com/news/nvidia-announces-strategic-partnership-with-lumentum-to-develop-state-of-the-art-optics-technology'},{title:'NVIDIA · Coherent and infrastructure',url:'https://blogs.nvidia.com/blog/nvidia-and-partners-build-in-america-for-america/'}]},
 {id:'packaging',name:'Packaging & test',subtitle:'CoWoS, chiplets & heterogeneous integration',phase:2,x:600,y:210,icon:'layers',companies:['TSM','ASX','AMKR'],description:'Advanced packaging connects logic, memory and other dies into a working module. Foundry packaging and outsourced assembly/test services serve different parts of this process.',output:'Packaged and tested accelerator modules',watch:'Interposer and substrate capacity, assembly yield and test throughput.',source:[fab,{title:'ASE · Advanced packaging (26 May 2026)',url:'https://ase.aseglobal.com/press-room/310x310/'},{title:'Amkor · AI packaging',url:'https://amkor.com/applications/artificial-intelligence/'}]},
 {id:'network',name:'Networking silicon',subtitle:'Switches, NICs & scale-out fabrics',phase:2,x:600,y:335,icon:'network',companies:['NVDA','AVGO','MRVL','ANET','CSCO'],description:'Network fabrics coordinate many accelerators across racks. Switch silicon, network adapters and complete switching systems are distinct product layers.',output:'Connected accelerator clusters',watch:'Congestion, latency, network bandwidth and interoperability at cluster scale.',source:[{title:'Arista · AI networking',url:'https://www.arista.com/en/solutions/ai-networking'},{title:'Arista & Broadcom · AI fabrics (9 Jun 2026)',url:'https://www.arista.com/company/news/press-release/24102-pr-20260609'},infra]},
 {id:'servers',name:'Servers & racks',subtitle:'System assembly and integration',phase:3,x:840,y:210,icon:'server',companies:['DELL','HPE','SMCI','2317.TW'],description:'System builders integrate accelerators, CPUs, memory, network adapters and cooling into servers and racks, then validate the complete system.',output:'Deployable AI servers and rack-scale systems',watch:'Component synchronization, rack validation, assembly capacity and deployment schedules.',source:[infra,{title:'NVIDIA · Manufacturing partners',url:'https://blogs.nvidia.com/blog/nvidia-and-partners-build-in-america-for-america/'}]},
 {id:'power',name:'Power & thermal',subtitle:'Electricity distribution and cooling',phase:3,x:840,y:335,icon:'power',companies:['VRT','ETN','SU.PA','GEV','TT'],description:'Electrical and cooling systems make high-density AI infrastructure operable. Power conversion, distribution, backup and heat removal must be engineered together.',output:'Powered and cooled compute capacity',watch:'Grid connection schedules, power availability and liquid-cooling readiness. Watchpoints are not live shortage measurements.',source:[infra]},
 {id:'cloud',name:'Hyperscalers & clouds',subtitle:'Training and inference deployment',phase:4,x:1080,y:85,icon:'cloud',companies:['MSFT','AMZN','GOOGL','ORCL','META','CRWV'],description:'Cloud providers turn infrastructure into compute services; Meta also deploys infrastructure for its own platforms. These are different business models within the deployment layer.',output:'Training clusters and inference services',watch:'Data-center readiness, utilization, customer demand and capital spending.',source:[{title:'NVIDIA · Blackwell cloud ecosystem',url:'https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing'},infra]},
 {id:'storage',name:'AI storage & data',subtitle:'Training data, checkpoints & context',phase:4,x:1080,y:335,icon:'database',companies:['NTAP','PSTG','IBM','VAST'],description:'Storage platforms keep data accessible for training and inference. Performance depends on moving data to compute quickly, not just total storage capacity.',output:'Data pipelines, model checkpoints and persistent context',watch:'Data throughput, metadata performance and integration with compute clusters.',source:[{title:'NVIDIA · AI data platform ecosystem',url:'https://nvidianews.nvidia.com/_gallery/download_pdf/67d9c8db3d6332e21fa36006/'}]},
];
export const aiFlows=[
 ['materials','foundry','Wafers'],['equipment','foundry','Process tools'],['eda','design','Design & IP'],['design','foundry','Tape-out'],['foundry','packaging','Logic dies'],['memory','packaging','HBM stacks'],['packaging','servers','Modules'],['optics','servers','Optical links'],['network','servers','Cluster fabric'],['power','servers','Power & cooling'],['servers','cloud','Compute capacity'],['storage','cloud','Data services'],['servers','storage','Storage systems'],
].map(([from,to,label])=>({from,to,label}));
export const phaseNames=['Foundations','Silicon & memory','Integration','Infrastructure','Deployment'];
export function stagesFor(symbol:string){return aiStages.filter(s=>s.companies.includes(symbol==='GOOG'?'GOOGL':symbol))}
