export type Business = {symbol:string;name:string;domain:string;role:string;usListed?:boolean};
export const businesses:Record<string,Business> = Object.fromEntries([
 ['NVDA','NVIDIA','nvidia.com','Accelerated computing'],['TSM','TSMC','tsmc.com','Semiconductor foundry'],['MU','Micron','micron.com','Memory & storage'],['ARM','Arm','arm.com','Processor architecture'],['MSFT','Microsoft','microsoft.com','Cloud & software'],['AMZN','Amazon','amazon.com','AWS & commerce'],['GOOGL','Alphabet','google.com','Google Cloud & AI'],['DELL','Dell Technologies','dell.com','Servers & systems'],['HPE','Hewlett Packard Enterprise','hpe.com','Enterprise infrastructure'],['AAPL','Apple','apple.com','Devices & services'],['AVGO','Broadcom','broadcom.com','Connectivity silicon'],['GLW','Corning','corning.com','Specialty glass'],['AMKR','Amkor','amkor.com','Chip packaging'],['COHR','Coherent','coherent.com','Optical components'],['AMD','AMD','amd.com','CPUs & accelerators'],['WMT','Walmart','walmart.com','Retail & commerce'],['TSLA','Tesla','tesla.com','EVs & energy'],['GM','General Motors','gm.com','Electric vehicles'],['F','Ford','ford.com','Electric vehicles'],['META','Meta','meta.com','Social platforms & AI'],['ORCL','Oracle','oracle.com','Cloud infrastructure'],
].map(([symbol,name,domain,role])=>[symbol,{symbol,name,domain,role,usListed:true}]));
businesses['6752.T']={symbol:'6752.T',name:'Panasonic',domain:'panasonic.com',role:'Battery cells · Tokyo listing',usListed:false};
const additionalBusinesses:[string,string,string,string,boolean][]=[
 ['4063.T','Shin-Etsu Chemical','shinetsu.co.jp','Silicon wafers · Tokyo',false],['3436.T','SUMCO','sumcosi.com','Silicon wafers · Tokyo',false],['ASML','ASML','asml.com','Lithography systems',true],['AMAT','Applied Materials','appliedmaterials.com','Semiconductor equipment',true],['LRCX','Lam Research','lamresearch.com','Etch & deposition',true],['KLAC','KLA','kla.com','Process control & inspection',true],['SNPS','Synopsys','synopsys.com','EDA & silicon IP',true],['CDNS','Cadence','cadence.com','Electronic design automation',true],['INTC','Intel','intel.com','Processors & foundry',true],['005930.KS','Samsung Electronics','samsung.com','Memory & foundry · Korea',false],['000660.KS','SK hynix','skhynix.com','High-bandwidth memory · Korea',false],['ASX','ASE Technology','aseglobal.com','Packaging & test · US ADR',true],['MRVL','Marvell','marvell.com','Custom silicon & connectivity',true],['LITE','Lumentum','lumentum.com','Photonics & lasers',true],['ANET','Arista Networks','arista.com','Cloud & AI networking',true],['CSCO','Cisco','cisco.com','Networking systems',true],['SMCI','Supermicro','supermicro.com','AI servers & racks',true],['2317.TW','Foxconn','foxconn.com','Systems manufacturing · Taiwan',false],['VRT','Vertiv','vertiv.com','Power & cooling',true],['ETN','Eaton','eaton.com','Power management',true],['SU.PA','Schneider Electric','se.com','Energy management · Paris',false],['GEV','GE Vernova','gevernova.com','Energy technology',true],['TT','Trane Technologies','tranetechnologies.com','Thermal management',true],['CRWV','CoreWeave','coreweave.com','AI cloud',true],['NTAP','NetApp','netapp.com','Data infrastructure',true],['PSTG','Pure Storage','purestorage.com','Data storage',true],['IBM','IBM','ibm.com','Enterprise infrastructure',true],['VAST','VAST Data','vastdata.com','Private company · no public ticker',false],
];
for(const [symbol,name,domain,role,usListed] of additionalBusinesses)businesses[symbol]={symbol,name,domain,role,usListed};
export type Link = {id:string;from:string;to:string;label:string;kind:'supply'|'deployment'|'partner';detail:string;source:string;publisher:string;date:string};
const blackwell='https://nvidianews.nvidia.com/news/nvidia-blackwell-platform-arrives-to-power-a-new-era-of-computing';
const apple='https://www.apple.com/newsroom/2025/08/apple-increases-us-commitment-to-600-billion-usd-announces-ambitious-program/';
const arm='https://newsroom.arm.com/blog/from-cloud-to-edge-arm-scales-your-ai-stack';
const links:Omit<Link,'id'>[]=[
 {from:'AMKR',to:'NVDA',label:'Advanced packaging partnership',kind:'supply',detail:'Amkor announced a multiyear packaging and test partnership with NVIDIA, including support for expanding US packaging capacity.',source:'https://ir.amkor.com/news-releases/news-release-details/amkor-technology-announces-strategic-partnership-nvidia-expand',publisher:'Amkor',date:'2026-07-23'},
 {from:'LITE',to:'NVDA',label:'Optics technology',kind:'partner',detail:'NVIDIA and Lumentum announced an optics technology partnership for AI infrastructure.',source:'https://nvidianews.nvidia.com/news/nvidia-announces-strategic-partnership-with-lumentum-to-develop-state-of-the-art-optics-technology',publisher:'NVIDIA',date:'2026-03'},
 {from:'AVGO',to:'ANET',label:'Ethernet switch silicon',kind:'supply',detail:'Arista describes Broadcom Tomahawk switch silicon in its next-generation AI networking systems.',source:'https://www.arista.com/company/news/press-release/24102-pr-20260609',publisher:'Arista',date:'2026-06-09'},

 {from:'TSM',to:'NVDA',label:'Chip fabrication',kind:'supply',detail:'NVIDIA identifies TSMC’s custom 4NP process as the manufacturing process for Blackwell GPUs.',source:blackwell,publisher:'NVIDIA',date:'2024-03-18'},
 {from:'MU',to:'NVDA',label:'High-bandwidth memory',kind:'supply',detail:'Micron describes HBM3E memory in NVIDIA B200 and B300 platforms, and SOCAMM collaboration for GB300.',source:'https://investors.micron.com/news/press-release/2025/Micron-Innovates-From-the-Data-Center-to-the-Edge-With-NVIDIA-03-18-2025/default.aspx',publisher:'Micron',date:'2025-03-18'},
 {from:'ARM',to:'NVDA',label:'CPU architecture',kind:'supply',detail:'NVIDIA’s Grace CPU uses Arm Neoverse technology in Grace Blackwell systems.',source:arm,publisher:'Arm',date:'2025'},
 ...[['MSFT','Azure'],['AMZN','AWS'],['GOOGL','Google Cloud'],['ORCL','Oracle Cloud']].map(([to,cloud])=>({from:'NVDA',to,label:'GPU cloud deployment',kind:'deployment' as const,detail:`${cloud} is named as a cloud provider for Blackwell-powered instances. This identifies platform adoption, not a disclosed purchase volume.`,source:blackwell,publisher:'NVIDIA',date:'2024-03-18'})),
 ...['DELL','HPE'].map(to=>({from:'NVDA',to,label:'Server integration',kind:'deployment' as const,detail:`${businesses[to].name} is named among manufacturers building systems with NVIDIA’s Blackwell platform.`,source:'https://nvidianews.nvidia.com/news/computer-industry-ai-factories-data-centers/',publisher:'NVIDIA',date:'2024-06-02'})),
 {from:'NVDA',to:'META',label:'AI infrastructure',kind:'deployment',detail:'NVIDIA reports a multiyear infrastructure partnership with Meta spanning CPUs, networking and Blackwell and Rubin GPUs.',source:'https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-fourth-quarter-and-fiscal-2026',publisher:'NVIDIA',date:'2026-02-25'},
 {from:'NVDA',to:'TSLA',label:'Announced AI adoption',kind:'deployment',detail:'NVIDIA named Tesla among organizations expected to adopt Blackwell at launch. The announcement does not disclose shipment or contract volumes.',source:blackwell,publisher:'NVIDIA',date:'2024-03-18'},
 {from:'TSM',to:'AAPL',label:'Apple silicon fabrication',kind:'supply',detail:'Apple identifies itself as a customer of TSMC’s Arizona fab, with Amkor planned to package the resulting Apple silicon.',source:'https://www.apple.com/newsroom/2023/11/apple-announces-expanded-partnership-with-amkor-for-silicon-packaging/',publisher:'Apple',date:'2023-11-30'},
 ...[['GLW','Cover glass','Corning supplies cover glass for Apple devices.'],['AVGO','Connectivity chips','Apple names Broadcom as a silicon manufacturing partner.'],['AMKR','Silicon packaging','Amkor is part of Apple’s American Manufacturing Program.'],['COHR','Optical components','Coherent produces VCSEL lasers used in features including Face ID.']].map(([from,label,detail])=>({from,to:'AAPL',label,kind:'supply' as const,detail,source:apple,publisher:'Apple',date:'2025-08-06'})),
 {from:'AMD',to:'MSFT',label:'Azure AI accelerators',kind:'supply',detail:'Azure offers ND MI300X virtual machines using AMD Instinct accelerators for AI workloads.',source:'https://learn.microsoft.com/en-us/azure/virtual-machines/accelerator-technologies/rocm-overview',publisher:'Microsoft Learn',date:'Undated documentation'},
 ...[['MSFT','Cobalt'],['AMZN','Graviton'],['GOOGL','Axion']].map(([to,chip])=>({from:'ARM',to,label:'Cloud CPU architecture',kind:'supply' as const,detail:`${businesses[to].name} uses Arm-based ${chip} processors for cloud infrastructure.`,source:arm,publisher:'Arm',date:'2025'})),
 {from:'MSFT',to:'WMT',label:'Azure AI services',kind:'deployment',detail:'Microsoft describes Walmart’s use of Azure OpenAI for search and an employee assistant.',source:'https://news.microsoft.com/ai-in-action',publisher:'Microsoft',date:'Undated customer showcase'},
 {from:'6752.T',to:'TSLA',label:'Battery manufacturing',kind:'supply',detail:'Tesla and Panasonic’s Gigafactory agreement describes Panasonic supplying cylindrical cells and Tesla assembling battery modules and packs. This is a historical agreement; current volumes are not supplied.',source:'https://ir.tesla.com/press-release/panasonic-and-tesla-sign-agreement-gigafactory',publisher:'Tesla',date:'2014-07-31'},
 {from:'TSLA',to:'GM',label:'Supercharger access',kind:'partner',detail:'GM opened Tesla Supercharger access for eligible EV drivers using an approved NACS adapter. This is a charging-network relationship, not a vehicle supply agreement.',source:'https://news.gm.com/home.detail.html/Pages/news/us/en/2024/sep/0918-nacs.html',publisher:'General Motors',date:'2024-09-18'},
 {from:'TSLA',to:'F',label:'Supercharger access',kind:'partner',detail:'Ford’s charging program includes access to Tesla Superchargers. This is a charging-network relationship, not a vehicle supply agreement.',source:'https://media.ford.com/content/dam/fordmedia/North%20America/CA/2025/02/Ford-Power-Promise-Fact-Sheet-English.pdf',publisher:'Ford',date:'2025-02'},
];
export const supplyLinks:Link[]=links.map(link=>({...link,id:`${link.from}-${link.to}`}));
export function networkFor(symbol:string){const ticker=symbol==='GOOG'?'GOOGL':symbol;return {company:businesses[ticker],incoming:supplyLinks.filter(l=>l.to===ticker),outgoing:supplyLinks.filter(l=>l.from===ticker)}};
