'use client';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronLeft,ChevronRight,Cloud,Code2,Cpu,Database,Factory,Gem,Layers3,MemoryStick,Network,Pause,Play,Plus,RotateCcw,Server,Unplug,X,Zap,ZoomIn,ZoomOut} from 'lucide-react';
import {industryEvidenceDates,summaryAiStages,summaryAiFlows,type ChainStage} from '@/lib/ai-supply-chain';
import {ecosystemFor,evidenceDatesFor} from '@/lib/company-ecosystem';
import {orderBySize,type CompanySize} from '@/lib/company-size';
import {businesses} from '@/lib/supply-chain';
import {StockLogo} from './stock-logo';
const icons={gem:Gem,factory:Factory,code:Code2,chip:Cpu,memory:MemoryStick,cable:Unplug,layers:Layers3,network:Network,server:Server,power:Zap,cloud:Cloud,database:Database};
const colors=['#91b4e5','#98bda8','#aaabdf','#d8b887','#72bdbd','#b6a4ca','#c4b58a'];
type Props={industry?:boolean;symbol:string;name:string;watchlist:{symbol:string;name:string}[];onExplore:(symbol:string)=>void;onAdd:(stock:{symbol:string;name:string})=>void};
export function AiEcosystem({symbol,name,watchlist,onExplore,onAdd,industry=false}:Props){
 const [currentOnly,setCurrentOnly]=useState(false);
 const [fullMap,setFullMap]=useState(false);
 useEffect(()=>{let active=true;if(industry)queueMicrotask(()=>{if(active)setFullMap(false)});return()=>{active=false}},[industry]);
 const ecosystem=useMemo(()=>ecosystemFor(symbol,name,industry,currentOnly),[symbol,name,industry,currentOnly]);
 const aiStages=industry&&!fullMap?summaryAiStages:ecosystem.stages,aiFlows=industry&&!fullMap?summaryAiFlows:ecosystem.flows,phaseNames=industry&&!fullMap?ecosystem.phases.slice(0,6):ecosystem.phases,tourOrder=aiStages.map(s=>s.id);
 const dates=ecosystem.kind==='industry'?industryEvidenceDates(aiStages):evidenceDatesFor(symbol,currentOnly);
 const [companySizes,setCompanySizes]=useState<Record<string,CompanySize>>({});
 const [sizeLoading,setSizeLoading]=useState(false);
 const formatDate=(value:string)=>new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z'));
 const mobileMap=useRef<HTMLDivElement>(null);
 const [mobileGeometry,setMobileGeometry]=useState<{width:number;height:number;paths:{from:string;to:string;d:string}[]}>({width:1,height:1,paths:[]});
 const viewport=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
 const [size,setSize]=useState({w:1200,h:420}),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[selected,setSelected]=useState<string|null>(null),[hover,setHover]=useState<string|null>(null),[motion,setMotion]=useState(true),[tour,setTour]=useState(false),[step,setStep]=useState(0),[focus,setFocus]=useState(false);
 const relevant=aiStages.filter(s=>s.companies.includes(symbol==='GOOG'?'GOOGL':symbol==='PSTG'?'P':symbol)).map(s=>s.id);const stage=aiStages.find(s=>s.id===selected);
 const sizeSymbols=stage?.companies.filter(t=>businesses[t]?.listingKind!=='private').slice().sort().join(',')||'';
 useEffect(()=>{if(!sizeSymbols)return;const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)setSizeLoading(true)});fetch('/api/supply-chain/size?symbols='+encodeURIComponent(sizeSymbols),{signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(!controller.signal.aborted)setCompanySizes(previous=>({...previous,...Object.fromEntries(((data as {sizes:CompanySize[]}).sizes).map(v=>[v.symbol,v]))}))}).catch(()=>{}).finally(()=>{if(!controller.signal.aborted)setSizeLoading(false)});return()=>controller.abort()},[sizeSymbols]);
 const worldWidth=phaseNames.length*240;
 const worldHeight=ecosystem.kind==='industry'?Math.max(420,...aiStages.map(stage=>stage.y+70)):Math.max(280,(size.h-32)*worldWidth/Math.max(size.w-24,1));
 function layoutStage(stage:ChainStage){if(ecosystem.kind==='industry'||compact)return stage;const peers=aiStages.filter(s=>s.phase===stage.phase).sort((a,b)=>a.y-b.y);const index=peers.findIndex(s=>s.id===stage.id);return {...stage,y:peers.length===1?worldHeight/2:85+index*(worldHeight-170)/(peers.length-1)}}
 const active=tour?tourOrder[step%tourOrder.length]:hover||selected;
 const neighbors=new Set(active?[active,...aiFlows.filter(f=>f.from===active||f.to===active).flatMap(f=>[f.from,f.to])]:[]);
 const [compact,setCompact]=useState(false),[phone,setPhone]=useState(false);
 useEffect(()=>{const mq=matchMedia('(max-width:600px)');const sync=()=>setPhone(mq.matches);sync();mq.addEventListener('change',sync);return()=>mq.removeEventListener('change',sync)},[]);
 useEffect(()=>{const mq=matchMedia('(max-width:767px)');const sync=()=>setCompact(mq.matches);sync();mq.addEventListener('change',sync);return()=>mq.removeEventListener('change',sync)},[]);
 useEffect(()=>{if(phone&&tour){document.getElementById(`mobile-stage-${tourOrder[step%tourOrder.length]}`)?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});return}if(compact&&tour){const current=aiStages.find(s=>s.id===tourOrder[step%tourOrder.length]);if(current)viewport.current?.scrollTo({left:Math.max(0,current.x-size.w/2),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}},[compact,phone,tour,step,size.w,aiStages,tourOrder]);
 useEffect(()=>{
  const root=mobileMap.current;if(!phone||!root)return;
  const measure=()=>{const bounds=root.getBoundingClientRect();const paths=aiFlows.flatMap(f=>{
   const from=root.querySelector(`#mobile-stage-${f.from} .ai-stage`)?.getBoundingClientRect();
   const to=root.querySelector(`#mobile-stage-${f.to} .ai-stage`)?.getBoundingClientRect();if(!from||!to)return [];
   const samePhase=aiStages.find(s=>s.id===f.from)?.phase===aiStages.find(s=>s.id===f.to)?.phase;
   if(samePhase){
    const right=to.left>from.left;const sx=(right?from.right:from.left)-bounds.left,tx=(right?to.left:to.right)-bounds.left;
    const sy=from.top-bounds.top+from.height/2,ty=to.top-bounds.top+to.height/2;
    return [{from:f.from,to:f.to,d:`M ${sx} ${sy} C ${(sx+tx)/2} ${sy}, ${(sx+tx)/2} ${ty}, ${tx} ${ty}`}];
   }
   const sx=from.left-bounds.left+from.width/2,tx=to.left-bounds.left+to.width/2;
   const sy=from.bottom-bounds.top,ty=to.top-bounds.top;
   return [{from:f.from,to:f.to,d:`M ${sx} ${sy} C ${sx} ${(sy+ty)/2}, ${tx} ${(sy+ty)/2}, ${tx} ${ty}`}];
  });setMobileGeometry({width:bounds.width,height:bounds.height,paths})};
  const observer=new ResizeObserver(measure);observer.observe(root);root.addEventListener('animationend',measure);measure();return()=>{observer.disconnect();root.removeEventListener('animationend',measure)};
 },[phone,symbol,aiFlows,aiStages]);
 const fit=Math.max(.1,Math.min((size.w-24)/worldWidth,(size.h-24)/worldHeight));const scale=fit*zoom;
 useEffect(()=>{if(!viewport.current)return;const ro=new ResizeObserver(([e])=>setSize({w:e.contentRect.width,h:e.contentRect.height}));ro.observe(viewport.current);return()=>ro.disconnect()},[]);
  useEffect(()=>{let active=true;queueMicrotask(()=>{if(active){setSelected(null);setFocus(false)}});return()=>{active=false}},[symbol,industry,currentOnly,fullMap]);
 useEffect(()=>{if(!tour||phone)return;const timer=setInterval(()=>setStep(v=>(v+1)%tourOrder.length),3500);return()=>clearInterval(timer)},[tour,phone,tourOrder.length]);
 function reset(){setZoom(1);setPan({x:0,y:0})}
 function path(from:ChainStage,to:ChainStage){from=layoutStage(from);to=layoutStage(to);const vertical=from.x===to.x;if(vertical){const sign=to.y>from.y?1:-1;return `M ${from.x} ${from.y+sign*56} C ${from.x} ${from.y+sign*78}, ${to.x} ${to.y-sign*78}, ${to.x} ${to.y-sign*56}`};const sign=to.x>from.x?1:-1;const sx=from.x+sign*92,tx=to.x-sign*92;return `M ${sx} ${from.y} C ${(sx+tx)/2} ${from.y}, ${(sx+tx)/2} ${to.y}, ${tx} ${to.y}`}
 function renderStage(s:ChainStage,i:number){const Icon=icons[s.icon as keyof typeof icons];const isRelevant=relevant.includes(s.id);return <button key={s.id} className={`ai-stage ${s.id===active?'active-stage':''} ${isRelevant?'stock-stage':''} ${(focus&&!isRelevant)||(active&&!neighbors.has(s.id))?'faded-stage':''}`} style={{left:s.x-92,top:layoutStage(s).y-56,'--phase-color':colors[s.phase],'--stage-delay':`${i*35}ms`} as CSSProperties} onClick={()=>{setSelected(s.id);setTour(false)}} onPointerEnter={e=>{if(e.pointerType==='mouse')setHover(s.id)}} onPointerLeave={()=>setHover(null)} aria-label={`Explore ${s.name}`} aria-pressed={selected===s.id}>
 <div className="ai-platform"><div className="platform-top"/><Icon size={26}/><span className="platform-shadow"/></div><h2>{s.name}</h2><p>{s.subtitle}</p><div className="ai-stage-tickers">{s.companies.slice(0,4).map(t=><span key={t} className={t===symbol?'chosen-ticker':''}><StockLogo symbol={t}/><small>{businesses[t]?.listingKind==='private'?'Private':t}</small></span>)}{s.companies.length>4&&<b>+{s.companies.length-4}</b>}</div>{isRelevant&&<span className="ai-selected-marker">{symbol}</span>}</button>}
 return <section className={`ai-explorer ${!motion?'ai-still':''}`} aria-label="Company ecosystem supply chain">
 <div className="ai-heading"><div><h1>{ecosystem.title} <span>/ {symbol}</span></h1><div className="ai-map-key"><span><i/>Industry flow</span>{relevant.length>0?<span><i className="key-stock"/>{symbol} participation</span>:<span>{symbol} is not mapped in this ecosystem</span>}{relevant.length>0&&<button aria-pressed={focus} onClick={()=>setFocus(v=>!v)}>{focus?'Show all layers':'Highlight '+symbol}</button>}</div><p>{ecosystem.kind==='industry'?'From materials and energy to real-world AI':'Disclosure-backed business connections'} <span>{aiStages.length} layers · {new Set(aiStages.flatMap(s=>s.companies)).size} companies</span></p></div><span className="ai-evidence-date" title="Latest publication among sources included in this company map; not a claim that every public disclosure has been collected.">Latest source: {dates.latestPublication?<time dateTime={dates.latestPublication}>{formatDate(dates.latestPublication)}</time>:'Publication date unavailable'}{dates.undatedSources>0&&<small>Some sources do not supply an exact publication date</small>}{dates.lastReviewed&&<small>Checked {formatDate(dates.lastReviewed)}</small>}</span><div className="ai-actions">{industry&&<div className={`ai-map-density ${fullMap?'is-full':''}`} role="group" aria-label="Map detail"><button aria-pressed={!fullMap} onClick={()=>{setFullMap(false);setTour(false);setStep(0);reset()}}>Compact</button><button aria-pressed={fullMap} onClick={()=>{setFullMap(true);setTour(false);setStep(0);reset()}}>Full</button></div>}{!industry&&<button aria-pressed={currentOnly} onClick={()=>{setCurrentOnly(v=>!v);setTour(false);setStep(0)}}>{currentOnly?'Recent disclosures':'Including historical'}</button>}<button onClick={()=>{setTour(v=>!v);setSelected(null);reset()}} aria-pressed={tour}>{tour?<Pause size={13}/>:<Play size={13}/>} Guided journey</button><button onClick={()=>setMotion(v=>!v)} aria-label={motion?'Pause flow animation':'Resume flow animation'}>{motion?<Pause size={13}/>:<Play size={13}/>}</button></div></div>
 {ecosystem.stages.length===1&&<p role="status" className="ai-coverage-note">{currentOnly?'Recent relationship evidence is not yet verified for':'The ecosystem has not been researched for'} {symbol}. No supplier or customer relationships are inferred from its ticker or industry.</p>}

 <div className={`ai-board-shell ${phone?'ai-vertical-board':''}`}>

 {phone&&<div key={`mobile-${industry}-${fullMap}`} ref={mobileMap} className="ai-mobile-phases ai-map-reveal" aria-label="AI supply chain phases, scroll down to explore">
 <svg className="ai-mobile-wires" viewBox={`0 0 ${mobileGeometry.width} ${mobileGeometry.height}`} aria-hidden="true"><defs><marker id="ai-mobile-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L5 3 L0 6" fill="none" stroke="#80bdb9"/></marker></defs>{mobileGeometry.paths.map((edge,i)=><g key={edge.from+edge.to} className={`ai-edge ${active&&(edge.from===active||edge.to===active)?'lit':''} ${active&&edge.from!==active&&edge.to!==active?'muted-edge':''}`} style={{'--flow-delay':`${-i*.43}s`} as CSSProperties}><path d={edge.d} className="ai-edge-track" markerEnd="url(#ai-mobile-arrow)"/><path d={edge.d} className="ai-edge-particles"/></g>)}</svg>
 {phaseNames.map((name,phase)=><section className="ai-mobile-phase" key={name} style={{'--phase-color':colors[phase]} as CSSProperties}><h2><span>0{phase+1}</span>{name}</h2><div className="ai-mobile-layers">{aiStages.filter(s=>s.phase===phase).map((s,i)=><div className="ai-mobile-layer" style={{gridColumn:Math.round((s.y-85)/125)%3+1,gridRow:Math.floor(Math.round((s.y-85)/125)/3)+1}} key={s.id} id={`mobile-stage-${s.id}`}>{renderStage(s,i)}</div>)}</div></section>)}
 </div>}

 <div className="ai-viewport" hidden={phone} ref={viewport} tabIndex={0} role="region" aria-label="AI supply chain map. Swipe to explore on mobile and tablet. On desktop, drag to pan, use plus and minus to zoom, and zero to fit." onKeyDown={e=>{if(e.target!==e.currentTarget||compact)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','0'].includes(e.key))e.preventDefault();if(e.key==='+')setZoom(z=>Math.min(3,z+.2));if(e.key==='-')setZoom(z=>Math.max(.6,z-.2));if(e.key==='0')reset();if(e.key.startsWith('Arrow'))setPan(p=>({x:p.x+(e.key==='ArrowLeft'?40:e.key==='ArrowRight'?-40:0),y:p.y+(e.key==='ArrowUp'?40:e.key==='ArrowDown'?-40:0)}))}} onPointerDown={e=>{if(compact)return;if((e.target as HTMLElement).closest('button,a'))return;drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current)setPan({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y})}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <div key={`world-${industry}-${fullMap}`} className="ai-world ai-map-reveal" style={{width:worldWidth,height:worldHeight,transform:`translate(${(size.w-worldWidth*scale)/2+pan.x}px, ${(size.h-worldHeight*scale)/2+pan.y}px) scale(${scale})`}}>
 {phaseNames.map((name,i)=><div key={name} className="ai-phase" style={{left:i*240+6,height:worldHeight-10,'--phase-color':colors[i]} as CSSProperties}><span>0{i+1} / {name}</span></div>)}
 <svg className="ai-flow-svg" style={{height:worldHeight}} viewBox={`0 0 ${worldWidth} ${worldHeight}`} aria-hidden="true"><defs><marker id="ai-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0 L7 3.5 L0 7" fill="none" stroke="#80a8b9"/></marker></defs>{aiFlows.map((edge,i)=>{const from=aiStages.find(s=>s.id===edge.from)!,to=aiStages.find(s=>s.id===edge.to)!;const lit=active&&(edge.from===active||edge.to===active);return <g key={edge.from+edge.to} className={`ai-edge ${lit?'lit':''} ${active&&!lit?'muted-edge':''}`} style={{'--flow-delay':`${-i*.43}s`} as CSSProperties}><path d={path(from,to)} className="ai-edge-track" markerEnd="url(#ai-arrow)"/><path d={path(from,to)} className="ai-edge-particles"/></g>})}</svg>
 {aiStages.map(renderStage)}
 </div></div>
 <div className="ai-map-controls"><button aria-label="Zoom out" disabled={zoom<=.6} onClick={()=>setZoom(z=>Math.max(.6,z-.2))}><ZoomOut size={15}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" disabled={zoom>=3} onClick={()=>setZoom(z=>Math.min(3,z+.2))}><ZoomIn size={15}/></button><button aria-label="Fit entire map" onClick={reset}><RotateCcw size={14}/> Fit</button></div>

 {tour&&<div className="ai-tour paper"><button aria-label="Previous journey step" onClick={()=>setStep(v=>(v+tourOrder.length-1)%tourOrder.length)}><ChevronLeft size={17}/></button><div><small>JOURNEY {step+1} / {tourOrder.length}</small><strong>{aiStages.find(s=>s.id===tourOrder[step%tourOrder.length])?.name}</strong><p>{aiStages.find(s=>s.id===tourOrder[step%tourOrder.length])?.output}</p></div><button aria-label="Next journey step" onClick={()=>setStep(v=>(v+1)%tourOrder.length)}><ChevronRight size={17}/></button><button aria-label="Close guided journey" onClick={()=>setTour(false)}><X size={15}/></button></div>}
 {stage&&<aside className="ai-stage-detail paper" aria-label={`${stage.name} details`}><button className="ai-close" aria-label="Close stage details" onClick={()=>setSelected(null)}><X size={17}/></button><div className="ai-detail-content"><span className="eyebrow">{phaseNames[stage.phase]} / LAYER DETAIL</span><h2>{stage.name}</h2><p>{stage.description}</p><div className="ai-output"><small>WHAT THIS LAYER DELIVERS</small><strong>{stage.output}</strong></div><h3>Companies in this layer</h3><p className="ai-size-note">{sizeLoading?'Loading company sizes…':'Largest companies first'}<small>Public companies ordered by company size. Private companies and unavailable sizes follow.</small></p><div className="ai-company-list">{orderBySize(stage.companies,companySizes).map(t=>{const b=businesses[t];if(!b)return null;const saved=watchlist.some(w=>w.symbol===t);return <div key={t}><StockLogo symbol={t}/><div><strong>{b.name}</strong><small>{b.listingKind==='private'?'Private · no public ticker':t+(b.usListed?' · US listing':' · International listing')}</small><small className="ai-company-role">{b.role}</small></div>{b.usListed?<><button aria-label={`Explore ${t} stock`} title={`View ${t} stock`} onClick={()=>onExplore(t)}><ArrowUpRight size={15}/></button><button aria-label={saved?`${t} in watchlist`:`Add ${t} to watchlist`} disabled={saved||watchlist.length>=24} onClick={()=>onAdd(b)}>{saved?<Check size={14}/>:<Plus size={14}/>}</button></>:<a aria-label={`Open ${b.name} website`} href={`https://${b.domain}`} target="_blank" rel="noopener noreferrer"><ArrowUpRight size={15}/></a>}</div>})}</div>{stage.processes&&<div className="ai-processes"><h3>Inside this layer</h3><ol>{stage.processes.map(process=><li key={process.name}><strong>{process.name}</strong><p>{process.detail}</p></li>)}</ol></div>}<div className="ai-watchpoint"><h3>Capacity watchpoints</h3><p>{stage.watch}</p><small>Structural factors to monitor, not a live bottleneck rating.</small></div><h3>Explore connected layers</h3><div className="ai-related">{aiFlows.filter(f=>f.from===stage.id||f.to===stage.id).map(f=>{const other=aiStages.find(s=>s.id===(f.from===stage.id?f.to:f.from))!;return <button key={f.from+f.to} onClick={()=>setSelected(other.id)}><span>{other.name}<small>{f.from===stage.id?'Receives: ':'Provides: '}{f.label}</small></span><ArrowRight size={13}/></button>})}</div><h3>Sources</h3><div className="ai-sources">{stage.source.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer"><span>{s.title}{(s.publicationDate||s.reviewedAt)&&<small className="ai-source-date">{s.publicationDate?'Published '+formatDate(s.publicationDate):'Publication date unavailable'}{s.reviewedAt?' · Checked '+formatDate(s.reviewedAt):''}</small>}</span><ArrowUpRight size={12}/></a>)}</div><small className="ai-disclosure">Industry examples do not establish a direct supplier contract with {symbol}. Use Company links for individually sourced relationships.</small></div></aside>}
 </div>
 </section>
}
