'use client';
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronLeft,ChevronRight,Cloud,Code2,Cpu,Database,Factory,Gem,Layers3,MemoryStick,Network,Pause,Play,Plus,RotateCcw,Server,Unplug,X,Zap,ZoomIn,ZoomOut} from 'lucide-react';
import {aiStages,aiFlows,phaseNames,stagesFor,type ChainStage} from '@/lib/ai-supply-chain';
import {businesses} from '@/lib/supply-chain';
import {StockLogo} from './stock-logo';
const icons={gem:Gem,factory:Factory,code:Code2,chip:Cpu,memory:MemoryStick,cable:Unplug,layers:Layers3,network:Network,server:Server,power:Zap,cloud:Cloud,database:Database};
const colors=['#91b4e5','#98bda8','#aaabdf','#d8b887','#72bdbd'];
const tourOrder=['materials','equipment','eda','design','foundry','memory','packaging','optics','network','power','servers','cloud','storage'];
type Props={symbol:string;name:string;watchlist:{symbol:string;name:string}[];onExplore:(symbol:string)=>void;onAdd:(stock:{symbol:string;name:string})=>void};
export function AiEcosystem({symbol,watchlist,onExplore,onAdd}:Props){
 const viewport=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;px:number;py:number}|null>(null);
 const [size,setSize]=useState({w:1200,h:420}),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[selected,setSelected]=useState<string|null>(null),[hover,setHover]=useState<string|null>(null),[motion,setMotion]=useState(true),[tour,setTour]=useState(false),[step,setStep]=useState(0),[focus,setFocus]=useState(false);
 const relevant=stagesFor(symbol).map(s=>s.id);const stage=aiStages.find(s=>s.id===selected);
 const active=tour?tourOrder[step]:hover||selected;
 const neighbors=new Set(active?[active,...aiFlows.filter(f=>f.from===active||f.to===active).flatMap(f=>[f.from,f.to])]:[]);
 const [compact,setCompact]=useState(false);
 useEffect(()=>{const mq=matchMedia('(max-width:1100px), (pointer:coarse) and (max-width:1366px)');const sync=()=>setCompact(mq.matches);sync();mq.addEventListener('change',sync);return()=>mq.removeEventListener('change',sync)},[]);
 useEffect(()=>{if(compact&&tour){const current=aiStages.find(s=>s.id===tourOrder[step]);if(current)viewport.current?.scrollTo({left:Math.max(0,current.x-size.w/2),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}},[compact,tour,step,size.w]);
 const fit=Math.min(size.w/1200,size.h/420);const scale=fit*zoom;
 useEffect(()=>{if(!viewport.current)return;const ro=new ResizeObserver(([e])=>setSize({w:e.contentRect.width,h:e.contentRect.height}));ro.observe(viewport.current);return()=>ro.disconnect()},[]);
 useEffect(()=>{setSelected(null);setFocus(false)},[symbol]);
 useEffect(()=>{if(!tour)return;const timer=setInterval(()=>setStep(v=>(v+1)%tourOrder.length),3500);return()=>clearInterval(timer)},[tour]);
 function reset(){setZoom(1);setPan({x:0,y:0})}
 function path(from:ChainStage,to:ChainStage){const vertical=from.x===to.x;if(vertical){const sign=to.y>from.y?1:-1;return `M ${from.x} ${from.y+sign*56} C ${from.x} ${from.y+sign*78}, ${to.x} ${to.y-sign*78}, ${to.x} ${to.y-sign*56}`};const sign=to.x>from.x?1:-1;const sx=from.x+sign*92,tx=to.x-sign*92;return `M ${sx} ${from.y} C ${(sx+tx)/2} ${from.y}, ${(sx+tx)/2} ${to.y}, ${tx} ${to.y}`}
 return <section className={`ai-explorer ${!motion?'ai-still':''}`} aria-label="Detailed AI supply chain">
 <div className="ai-heading"><div><h1>AI chip supply chain <span>/ {symbol}</span></h1><p>From silicon to intelligence <span>13 layers · {new Set(aiStages.flatMap(s=>s.companies)).size} companies</span></p></div><div className="ai-actions"><button onClick={()=>{setTour(v=>!v);setSelected(null);reset()}} aria-pressed={tour}>{tour?<Pause size={13}/>:<Play size={13}/>} Guided journey</button><button onClick={()=>setMotion(v=>!v)} aria-label={motion?'Pause flow animation':'Resume flow animation'}>{motion?<Pause size={13}/>:<Play size={13}/>}</button></div></div>
 <div className="ai-board-shell">
 <div className="ai-viewport" ref={viewport} tabIndex={0} role="region" aria-label="AI supply chain map. Swipe to explore on mobile and tablet. On desktop, drag to pan, use plus and minus to zoom, and zero to fit." onKeyDown={e=>{if(e.target!==e.currentTarget||compact)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','0'].includes(e.key))e.preventDefault();if(e.key==='+')setZoom(z=>Math.min(3,z+.2));if(e.key==='-')setZoom(z=>Math.max(.6,z-.2));if(e.key==='0')reset();if(e.key.startsWith('Arrow'))setPan(p=>({x:p.x+(e.key==='ArrowLeft'?40:e.key==='ArrowRight'?-40:0),y:p.y+(e.key==='ArrowUp'?40:e.key==='ArrowDown'?-40:0)}))}} onPointerDown={e=>{if(compact)return;if((e.target as HTMLElement).closest('button,a'))return;drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current)setPan({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y})}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <div className="ai-world" style={{transform:`translate(${(size.w-1200*scale)/2+pan.x}px, ${(size.h-420*scale)/2+pan.y}px) scale(${scale})`}}>
 {phaseNames.map((name,i)=><div key={name} className="ai-phase" style={{left:i*240+6,'--phase-color':colors[i]} as CSSProperties}><span>0{i+1} / {name}</span></div>)}
 <svg className="ai-flow-svg" viewBox="0 0 1200 420" aria-hidden="true"><defs><marker id="ai-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0 L7 3.5 L0 7" fill="none" stroke="#80a8b9"/></marker></defs>{aiFlows.map((edge,i)=>{const from=aiStages.find(s=>s.id===edge.from)!,to=aiStages.find(s=>s.id===edge.to)!;const lit=active&&(edge.from===active||edge.to===active);return <g key={edge.from+edge.to} className={`ai-edge ${lit?'lit':''} ${active&&!lit?'muted-edge':''}`} style={{'--flow-delay':`${-i*.43}s`} as CSSProperties}><path d={path(from,to)} className="ai-edge-track" markerEnd="url(#ai-arrow)"/><path d={path(from,to)} className="ai-edge-particles"/></g>})}</svg>
 {aiStages.map((s,i)=>{const Icon=icons[s.icon as keyof typeof icons];const isRelevant=relevant.includes(s.id);return <button key={s.id} className={`ai-stage ${s.id===active?'active-stage':''} ${isRelevant?'stock-stage':''} ${(focus&&!isRelevant)||(active&&!neighbors.has(s.id))?'faded-stage':''}`} style={{left:s.x-92,top:s.y-56,'--phase-color':colors[s.phase],'--stage-delay':`${i*35}ms`} as CSSProperties} onClick={()=>{setSelected(s.id);setTour(false)}} onPointerEnter={e=>{if(e.pointerType==='mouse')setHover(s.id)}} onPointerLeave={()=>setHover(null)} aria-label={`Explore ${s.name}`} aria-pressed={selected===s.id}>
 <div className="ai-platform"><div className="platform-top"/><Icon size={26}/><span className="platform-shadow"/></div><h2>{s.name}</h2><p>{s.subtitle}</p><div className="ai-stage-tickers">{s.companies.slice(0,4).map(t=><span key={t} className={t===symbol?'chosen-ticker':''}><StockLogo symbol={t}/><small>{t==='VAST'?'Private':t}</small></span>)}{s.companies.length>4&&<b>+{s.companies.length-4}</b>}</div>{isRelevant&&<span className="ai-selected-marker">{symbol}</span>}</button>})}
 </div></div>
 <div className="ai-map-controls"><button aria-label="Zoom out" disabled={zoom<=.6} onClick={()=>setZoom(z=>Math.max(.6,z-.2))}><ZoomOut size={15}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" disabled={zoom>=3} onClick={()=>setZoom(z=>Math.min(3,z+.2))}><ZoomIn size={15}/></button><button aria-label="Fit entire map" onClick={reset}><RotateCcw size={14}/> Fit</button></div>
 <div className="ai-map-key"><span><i/>Industry flow</span>{relevant.length>0?<span><i className="key-stock"/>{symbol} participation</span>:<span>{symbol} is not mapped in this ecosystem</span>}{relevant.length>0&&<button aria-pressed={focus} onClick={()=>setFocus(v=>!v)}>{focus?'Show all layers':'Highlight '+symbol}</button>}</div>
 {tour&&<div className="ai-tour paper"><button aria-label="Previous journey step" onClick={()=>setStep(v=>(v+12)%13)}><ChevronLeft size={17}/></button><div><small>JOURNEY {step+1} / 13</small><strong>{aiStages.find(s=>s.id===tourOrder[step])?.name}</strong><p>{aiStages.find(s=>s.id===tourOrder[step])?.output}</p></div><button aria-label="Next journey step" onClick={()=>setStep(v=>(v+1)%13)}><ChevronRight size={17}/></button><button aria-label="Close guided journey" onClick={()=>setTour(false)}><X size={15}/></button></div>}
 {stage&&<aside className="ai-stage-detail paper" aria-label={`${stage.name} details`}><button className="ai-close" aria-label="Close stage details" onClick={()=>setSelected(null)}><X size={17}/></button><span className="eyebrow">{phaseNames[stage.phase]} / LAYER DETAIL</span><h2>{stage.name}</h2><p>{stage.description}</p><div className="ai-output"><small>WHAT THIS LAYER DELIVERS</small><strong>{stage.output}</strong></div><h3>Companies in this layer</h3><div className="ai-company-list">{stage.companies.map(t=>{const b=businesses[t];const saved=watchlist.some(w=>w.symbol===t);return <div key={t}><StockLogo symbol={t}/><div><strong>{b.name}</strong><small>{t==='VAST'?'Private · no public ticker':t+(b.usListed?' · US listing':' · International listing')}</small></div>{b.usListed?<><button aria-label={`Explore ${t} stock`} title={`View ${t} stock`} onClick={()=>onExplore(t)}><ArrowUpRight size={15}/></button><button aria-label={saved?`${t} in watchlist`:`Add ${t} to watchlist`} disabled={saved||watchlist.length>=24} onClick={()=>onAdd(b)}>{saved?<Check size={14}/>:<Plus size={14}/>}</button></>:<a aria-label={`Open ${b.name} website`} href={`https://${b.domain}`} target="_blank" rel="noopener noreferrer"><ArrowUpRight size={15}/></a>}</div>})}</div><div className="ai-watchpoint"><h3>Capacity watchpoints</h3><p>{stage.watch}</p><small>Structural factors to monitor, not a live bottleneck rating.</small></div><h3>Explore connected layers</h3><div className="ai-related">{aiFlows.filter(f=>f.from===stage.id||f.to===stage.id).map(f=>{const other=aiStages.find(s=>s.id===(f.from===stage.id?f.to:f.from))!;return <button key={f.from+f.to} onClick={()=>setSelected(other.id)}><span>{other.name}<small>{f.from===stage.id?'Receives: ':'Provides: '}{f.label}</small></span><ArrowRight size={13}/></button>})}</div><h3>Sources</h3><div className="ai-sources">{stage.source.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.title}<ArrowUpRight size={12}/></a>)}</div><small className="ai-disclosure">Industry examples do not establish a direct supplier contract with {symbol}. Use Company links for individually sourced relationships.</small></aside>}
 </div><div className="ai-footnote"><span>{compact?'Swipe sideways to explore · tap a layer for companies & sources':'Drag to pan · + / − to zoom · click a layer for companies & sources'}</span><span>Curated industry map · reviewed 02/10/2026 · not a live supply feed</span></div>
 </section>
}
