'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {Market} from '@/lib/market';
type Item=Market['news'][number];
export function NewsFeed({symbol}:{symbol:string}){const [items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[next,setNext]=useState<number|null>(0),[pending,setPending]=useState<Item[]>([]);const root=useRef<HTMLDivElement>(null),end=useRef<HTMLDivElement>(null),busy=useRef(false),current=useRef<Item[]>([]),controller=useRef<AbortController|null>(null);
const load=useCallback(async(offset:number,refresh=false)=>{if(busy.current)return;busy.current=true;controller.current=new AbortController();setLoading(true);setError('');try{const response=await fetch(`/api/news?symbol=${encodeURIComponent(symbol)}&offset=${offset}`,{signal:controller.current.signal});if(!response.ok)throw Error('News is temporarily unavailable.');const result=await response.json() as {items:Item[];nextOffset:number|null};if(refresh){const fresh=result.items.filter(n=>!current.current.some(v=>v.url===n.url));if(fresh.length)setPending(old=>[...new Map([...fresh,...old].map(n=>[n.url,n])).values()]);}else{const merged=[...new Map([...current.current,...result.items].map(n=>[n.url,n])).values()];current.current=merged;setItems(merged);setNext(result.nextOffset)}}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setError('Could not load more news. Please retry.')}finally{busy.current=false;setLoading(false)}},[symbol]);
useEffect(()=>{load(0);const timer=setInterval(()=>load(0,true),120000);return()=>{clearInterval(timer);controller.current?.abort()}},[load]);
useEffect(()=>{if(!end.current||!root.current||next===null||loading||error)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting)load(next)},{root:root.current,rootMargin:'0px 0px 160px 0px'});observer.observe(end.current);return()=>observer.disconnect()},[next,loading,error,load]);
return <div className="news-list" ref={root} tabIndex={0} role="region" aria-label="Scrollable company news" aria-busy={loading}>{pending.length>0&&<button className="new-news" onClick={()=>{const merged=[...new Map([...pending,...current.current].map(n=>[n.url,n])).values()];current.current=merged;setItems(merged);setPending([]);root.current?.scrollTo({top:0,behavior:'smooth'})}}>{pending.length} new {pending.length===1?'story':'stories'} · Show latest</button>}{items.map(n=><article key={n.url}><p className="news-meta">{n.source} · {new Date(n.datetime*1000).toLocaleDateString('en-US',{month:'short',day:'numeric',timeZone:'America/New_York'})}</p><h3><a href={n.url} target="_blank" rel="noopener noreferrer">{n.headline}</a></h3>{n.summary&&<p className="news-summary">{n.summary}</p>}<a href={n.url} target="_blank" rel="noopener noreferrer">Read original</a></article>)}<div ref={end} className="news-feed-status" aria-live="polite">{loading?'Loading news…':error?<><span>{error}</span><button onClick={()=>load(next??0)}>Retry</button></>:next!==null?<button onClick={()=>load(next)}>Load more stories</button>:items.length?'You’re up to date. Checking for new stories automatically.':'No recent stories available for this stock.'}</div></div>}
