'use client';
import {useState,type CSSProperties} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronLeft,ChevronRight,Network,Pause,Play,Plus} from 'lucide-react';
import {businesses,networkFor,type Link} from '@/lib/supply-chain';
import {StockLogo} from './stock-logo';
import {AiEcosystem} from './ai-ecosystem';
type Props={symbol:string;name:string;watchlist:{symbol:string;name:string}[];onExplore:(symbol:string)=>void;onAdd:(stock:{symbol:string;name:string})=>void};
export function SupplyChain(props:Props){const [mode,setMode]=useState<'ecosystem'|'company'|'industry'>('ecosystem');return <div className="supply-shell"><div className="supply-mode" role="group" aria-label="Supply chain view"><button aria-pressed={mode==='ecosystem'} onClick={()=>setMode('ecosystem')}>Ecosystem</button><button aria-pressed={mode==='company'} onClick={()=>setMode('company')}>Company links</button><button aria-pressed={mode==='industry'} onClick={()=>setMode('industry')}>AI industry map</button><span>{mode==='ecosystem'?'Industry layers · select a stage to explore':'Source-backed company relationships'}</span></div>{mode!=='company'?<AiEcosystem {...props} industry={mode==='industry'}/>:<SupplyMap key={props.symbol} {...props}/>}</div>}
function SupplyMap({symbol,name,watchlist,onExplore,onAdd}:Props){
 const {company,incoming,outgoing}=networkFor(symbol);
 const [selected,setSelected]=useState<Link|null>(null),[hover,setHover]=useState<string|null>(null),[paused,setPaused]=useState(false),[leftPage,setLeftPage]=useState(0),[rightPage,setRightPage]=useState(0);
 const ticker=company?.symbol||symbol;const connected=incoming.length+outgoing.length;
 const peer=selected?businesses[selected.from===ticker?selected.to:selected.from]:null;
 const inWatchlist=peer&&watchlist.some(c=>c.symbol===peer.symbol);
 const sides=[{key:'incoming',items:incoming,page:leftPage,set:setLeftPage,x:16,title:'Inputs & technology',subtitle:'Suppliers and enabling platforms'},{key:'outgoing',items:outgoing,page:rightPage,set:setRightPage,x:84,title:'Deployment & partners',subtitle:'Where products and services go'}];
 const nodes=sides.flatMap(side=>side.items.slice(side.page*4,side.page*4+4).map((link,i,arr)=>({link,x:side.x,y:arr.length===1?50:14+i*72/(arr.length-1),business:businesses[side.key==='incoming'?link.from:link.to],side:side.key})));
 const active=hover||selected?.id;
 return <section className={`supply-view ${paused?'motion-paused':''}`} aria-label={`${symbol} supply chain`}>
  <div className="supply-header"><div><span className="eyebrow">BUSINESS CONNECTIONS</span><h1>Supply chain <span>/ {symbol}</span></h1></div><div className="supply-tools"><span>{connected} documented connections</span><button onClick={()=>setPaused(p=>!p)} aria-label={paused?'Play animation':'Pause animation'}>{paused?<Play size={14}/>:<Pause size={14}/>}<span>{paused?'Play':'Pause'}</span></button></div></div>
  <div className="supply-workspace"><div className="supply-map-panel panel"><div className="supply-map-scroll" tabIndex={0} aria-label="Business relationship map"><div className="supply-map">
   <div className="supply-stage-heads">{sides.map(side=><div key={side.key} className={side.key}><span className="eyebrow">{side.key==='incoming'?'01':'03'} / {side.title}</span><small>{side.subtitle}</small>{side.items.length>4&&<div className="chain-pager"><button disabled={side.page===0} onClick={()=>side.set(p=>p-1)} aria-label={`Previous ${side.key} connections`}><ChevronLeft size={13}/></button><span>{side.page+1}/{Math.ceil(side.items.length/4)}</span><button disabled={(side.page+1)*4>=side.items.length} onClick={()=>side.set(p=>p+1)} aria-label={`Next ${side.key} connections`}><ChevronRight size={13}/></button></div>}</div>)}<div className="focal-stage"><span className="eyebrow">02 / THE BUSINESS</span><small>Follow the connections</small></div></div>
   <div className="chain-canvas"><svg className="chain-wires" viewBox="0 0 1000 400" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="chain-arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 L8 4 L0 8" fill="none" stroke="currentColor"/></marker></defs>{nodes.map(({link,x,y})=>{const d=x<50?`M 270 ${y*4} C 335 ${y*4}, 335 200, 390 200`:`M 610 200 C 670 200, 665 ${y*4}, 730 ${y*4}`;return <g key={link.id} className={`chain-wire ${link.kind} ${active===link.id?'highlighted':''} ${active&&active!==link.id?'dimmed':''}`}><path d={d} className="wire-base" markerEnd="url(#chain-arrow)"/><path d={d} className="wire-flow"/></g>})}</svg>
   <div className="chain-orbit"/>
   <div className="chain-center paper"><span className="chain-center-label">SELECTED COMPANY</span><StockLogo symbol={symbol} large/><h2>{symbol}</h2><p>{company?.name||name}</p><small>{company?.role||'US equity'}</small><span className="chain-center-count"><Network size={12}/>{connected} connections</span></div>
   {nodes.map(({link,x,y,business},i)=><button key={link.id} className={`chain-node ${link.kind} ${selected?.id===link.id?'is-selected':''}`} style={{left:`${x}%`,top:`${y}%`,'--node-delay':`${i*45}ms`} as CSSProperties} onClick={()=>setSelected(link)} onMouseEnter={()=>setHover(link.id)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(link.id)} onBlur={()=>setHover(null)} aria-pressed={selected?.id===link.id} aria-label={`${business.name}: ${link.label}`}><StockLogo symbol={business.symbol}/><span className="chain-node-copy"><strong>{business.symbol}<ArrowUpRight size={12}/></strong><span>{business.name}</span><small>{link.label}</small></span></button>)}
   {sides.map(side=>!side.items.length&&<div key={side.key} className={`chain-no-links ${side.key}`}><span>Connections not yet mapped</span><small>Coverage is selective</small></div>)}
   </div></div></div><div className="chain-legend"><span><i/>Supply / technology</span><span><i className="deployment"/>Deployment</span><span><i className="partner"/>Partnership</span><small>Arrows follow products or services</small></div></div>
  <aside className="chain-detail paper" aria-live="polite">{selected&&peer?<><span className="eyebrow">CONNECTION DETAIL</span><div className="chain-detail-company"><StockLogo symbol={peer.symbol}/><div><h2>{peer.symbol}</h2><span>{peer.name}</span></div></div><span className={`relationship-type ${selected.kind}`}>{selected.kind==='supply'?'Supply / technology':selected.kind==='deployment'?'Deployment':'Partnership'}</span><h3>{selected.label}</h3><div className="chain-direction">{selected.from}<ArrowRight size={14}/>{selected.to}</div><p>{selected.detail}</p><a className="chain-source" href={selected.source} target="_blank" rel="noopener noreferrer">{selected.publisher} · Read source <ArrowUpRight size={13}/></a><small>Source date: {selected.date}</small><div className="chain-detail-actions">{peer.usListed?<><button onClick={()=>onExplore(peer.symbol)}>Explore {peer.symbol}<ArrowRight size={14}/></button><button disabled={!!inWatchlist||watchlist.length>=24} onClick={()=>onAdd(peer)}>{inWatchlist?<Check size={14}/>:<Plus size={14}/>} {inWatchlist?'In watchlist':watchlist.length>=24?'Watchlist full':'Add to watchlist'}</button></>:<small>{peer.listingKind==='private'?'Private company · no public ticker':'International listing · US watchlist only'}</small>}</div></>:<><span className="eyebrow">THE BIGGER PICTURE</span><Network className="chain-detail-icon" size={40}/><h2>{connected?'Every company has a network.':'This map is still growing.'}</h2><p>{connected?'Trace the suppliers, platforms and business partners connected to '+(company?.name||name)+'. Select a company on the map to see the relationship and its source.':'Verified connections for '+symbol+' are not yet in this collection. Choose a mapped company below to explore its network.'}</p><div className="chain-examples">{['NVDA','AAPL','MSFT','TSLA'].filter(s=>s!==symbol).map(s=><button key={s} onClick={()=>onExplore(s)}><StockLogo symbol={s}/>{s}<ArrowRight size={12}/></button>)}</div></>}<div className="chain-disclosure">Curated public disclosures · Reviewed 02/10/2026<br/>Selective coverage, not a complete supplier list. Connections do not imply stock-price correlation or current contract volumes.</div></aside></div>
 </section>
}
