"use client";
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {getSupabaseBrowserClient} from '@/lib/supabase-browser';
type ExportData={account:{email?:string};watchlist:unknown[];deletionAvailable:boolean;exportedAt:string};
export function AccountControls(){
 const [data,setData]=useState<ExportData|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmation,setConfirmation]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const controller=new AbortController();async function load(){try{const {data:session}=await getSupabaseBrowserClient()?.auth.getSession()??{data:{session:null}};if(!session.session){setError('Please sign in to manage your account.');return}const response=await fetch('/api/account',{headers:{Authorization:`Bearer ${session.session.access_token}`},cache:'no-store',signal:controller.signal});const result=await response.json() as ExportData&{error?:string};if(!response.ok)throw Error(result.error||'Account data unavailable.');setData(result)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Account data unavailable.')}finally{if(!controller.signal.aborted)setLoading(false)}}void load();return()=>controller.abort()},[]);
 function download(){if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='moonstar-account.json';a.click();URL.revokeObjectURL(url)}
 function clearLocal(){for(const storage of [localStorage,sessionStorage]){for(let i=storage.length-1;i>=0;i--){const key=storage.key(i);if(key&&(key.startsWith('moonstar_')||key.startsWith('market-after-hours-')))storage.removeItem(key)}}setMessage('Local preferences and guest data cleared. Your server account has not been deleted. Reload the dashboard to use the defaults.')}
 async function remove(){setBusy(true);setError('');try{const client=getSupabaseBrowserClient(),{data:session}=await client?.auth.getSession()??{data:{session:null}};if(!session.session)throw Error('Please sign in again.');const response=await fetch('/api/account',{method:'DELETE',headers:{Authorization:`Bearer ${session.session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({confirmation})});const result=await response.json() as {error?:string;deleted?:boolean};if(!response.ok||!result.deleted)throw Error(result.error||'Deletion could not be confirmed.');await client?.auth.signOut({scope:'local'});clearLocal();for(const storage of [localStorage,sessionStorage]){const ref=new URL(process.env.NEXT_PUBLIC_SUPABASE_URL||window.location.origin).hostname.split('.')[0];for(let i=storage.length-1;i>=0;i--){const key=storage.key(i);if(key?.startsWith(`sb-${ref}-auth-token`))storage.removeItem(key)}}setData(null);setMessage('Your account and linked server watchlist were deleted. Provider logs and backups follow their retention policies.')}catch(e){setError(e instanceof Error?e.message:'Deletion failed.')}finally{setBusy(false)}}
 return <><p>Export your saved data or manage account deletion. Clearing browser data and deleting the server account are separate actions.</p>{loading?<p role="status">Loading account…</p>:data?<><p>Signed in as {data.account.email}. Saved stocks: {data.watchlist.length}.</p><div className="account-actions"><button onClick={download} disabled={busy}>Download my data</button><button onClick={clearLocal} disabled={busy}>Clear local preferences</button></div><section className="account-confirm"><h2>Delete account</h2><p>This permanently removes your active account and its linked watchlist. Sign in again before deleting; recent authentication is required.</p>{data.deletionAvailable?<><label htmlFor="delete-confirm">Type DELETE to confirm</label><input id="delete-confirm" value={confirmation} autoComplete="off" onChange={e=>setConfirmation(e.target.value)}/><button className="account-danger" disabled={confirmation!=='DELETE'||busy} onClick={remove}>{busy?'Deleting…':'Delete my account'}</button></>:<p>Self-service deletion is awaiting secure administration setup. Refer to the operator contact in the privacy notice.</p>}</section></>:<p><Link href="/login">Sign in</Link></p>}{error&&<p className="account-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</>;
}
