import {earningsSchedule} from '@/lib/earnings-calendar';
import YahooFinance from 'yahoo-finance2';
import {companies,type Market} from '@/lib/market';
const cache=new Map<string,{expires:number;value:any}>();
async function cached(key:string,ttl:number,fn:()=>Promise<any>){const existing=cache.get(key);if(existing&&existing.expires>Date.now())return existing.value;const value=await fn();cache.set(key,{expires:Date.now()+ttl,value});return value;}
const num=(x:any):number|null=>typeof x==='number'&&Number.isFinite(x)?x:null;
const stamp=(x:any):number|null=>{const n=new Date(x).getTime();return Number.isFinite(n)?n:null};
function period(x:any){const date=new Date(x);return `Q${Math.floor(date.getUTCMonth()/3)+1} ’${String(date.getUTCFullYear()).slice(-2)}`}

function clean(s:string){return s.replace(/<[^>]*>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').trim()}
async function excerpt(url:string){try{const u=new URL(url);if(u.hostname!=='finance.yahoo.com')return '';const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(5000)});if(!r.ok)return '';const html=(await r.text()).slice(0,500000);const tag=html.match(/<meta\b[^>]*(?:name|property)=["'](?:description|og:description)["'][^>]*>/i)?.[0];const value=tag?.match(/content=["']([\s\S]*?)["']\s*\/?\s*>/i)?.[1];return value?clean(value).slice(0,420):''}catch{return ''}}
export async function GET(request:Request){const p=new URL(request.url).searchParams,symbol=(p.get('symbol')||'NVDA').toUpperCase(),range=p.get('range')||'1D';if(!/^[A-Z][A-Z0-9.-]{0,11}$/.test(symbol))return Response.json({error:'Invalid symbol'},{status:400});const co=companies.find(c=>c.symbol===symbol)||{name:symbol,sector:'US equity',description:'Company description not supplied.'};const ranges:Record<string,[string,string]>={'1D':['1d','5m'],'1W':['5d','30m'],'1M':['1mo','1d'],'3M':['3mo','1d'],'1Y':['1y','1d'],'5Y':['5y','1wk']};if(!ranges[range])return Response.json({error:'Unsupported range'},{status:400});const [r,interval]=ranges[range];
const yahoo=new YahooFinance({suppressNotices:['yahooSurvey','ripHistorical']});if(!cache.get(`${symbol}:summary`)||cache.get(`${symbol}:summary`)!.expires<Date.now())await yahoo.quote(symbol).catch(()=>{});const results=await Promise.allSettled([
cached(`${symbol}:chart:${range}`,55000,async()=>{const response=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}?interval=${interval}&range=${r}`,{headers:{'User-Agent':'Mozilla/5.0'},signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('Price feed unavailable');const json=await response.json() as any;const result=json.chart?.result?.[0];if(!result)throw Error('No chart data');return result}),
cached(`${symbol}:summary`,300000,()=>yahoo.quoteSummary(symbol,{modules:['price','summaryDetail','defaultKeyStatistics','financialData','earningsHistory','earningsTrend','assetProfile','calendarEvents']},{validateResult:false})),
cached(`${symbol}:news`,300000,async()=>{const result:any=await yahoo.search(symbol,{newsCount:6,quotesCount:0},{validateResult:false});return Promise.all((result.news||[]).filter((n:any)=>n.relatedTickers?.includes(symbol)&&/^https:\/\//.test(n.link)).slice(0,3).map(async(n:any)=>({headline:n.title,summary:await excerpt(n.link),source:n.publisher,url:n.link,datetime:(stamp(n.providerPublishTime)||0)/1000})))})]);
if(results[1].status==='rejected') console.error('Summary fetch:',String(results[1].reason));const chart=results[0].status==='fulfilled'?results[0].value:null;const summary=results[1].status==='fulfilled'?results[1].value:null;const news=results[2].status==='fulfilled'?results[2].value:[];const pr=summary?.price,detail=summary?.summaryDetail,financial=summary?.financialData,meta=chart?.meta;const price=num(meta?.regularMarketPrice)??num(pr?.regularMarketPrice);if(price===null)return Response.json({error:'Yahoo Finance is temporarily unavailable. Please try again.'},{status:503});const previous=num(meta?.previousClose)??num(pr?.regularMarketPreviousClose);const history=summary?.earningsHistory?.history||[];const earnings=history.slice(-4).map((e:any)=>({period:period(e.quarter),actual:num(e.epsActual),estimate:num(e.epsEstimate)}));const next=summary?.earningsTrend?.trend?.find((t:any)=>t.period==='0q');if(next)earnings.push({period:period(next.endDate),actual:null,estimate:num(next.earningsEstimate?.avg),...earningsSchedule(summary?.calendarEvents?.earnings)});const quotes=chart?.indicators?.quote?.[0];const points=(chart?.timestamp||[]).map((time:number,i:number)=>({time:time*1000,price:num(quotes?.close?.[i]),volume:num(quotes?.volume?.[i])??0})).filter((p:any)=>p.price!==null);const warnings=[];if(!summary)warnings.push('Valuation, targets, and earnings are temporarily unavailable from Yahoo Finance.');if(!news.length)warnings.push('No recent news returned.');if(!chart)warnings.push('Historical chart unavailable.');const data:Market={symbol,name:pr?.longName||meta?.longName||co.name,sector:summary?.assetProfile?.sector||co.sector,description:summary?.assetProfile?.longBusinessSummary?.split(/(?<=\.)\s+/).slice(0,2).join(' ')||co.description,price,change:previous!==null?price-previous:num(pr?.regularMarketChange),percent:previous?((price/previous)-1)*100:(num(pr?.regularMarketChangePercent)===null?null:pr.regularMarketChangePercent*100),timestamp:meta?.regularMarketTime?meta.regularMarketTime*1000:stamp(pr?.regularMarketTime),mode:'connected',exchange:pr?.exchangeName||meta?.fullExchangeName||'US equity',pe:num(detail?.trailingPE),forwardPe:num(detail?.forwardPE)??num(summary?.defaultKeyStatistics?.forwardPE),target:num(financial?.targetMeanPrice),targetDate:null,volume:num(meta?.regularMarketVolume)??num(detail?.volume),averageVolume:num(detail?.averageVolume),points,earnings,news,warnings,delayMinutes:num(pr?.exchangeDataDelayedBy),retrievedAt:Date.now()};return Response.json(data,{headers:{'Cache-Control':'private, max-age=30'}});
}
